# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/user/foreign/uavcanv1-influxdb-writer/public_regulated_data_types/uavcan/node/435.ExecuteCommand.1.0.uavcan
#
# Generated at:  2021-11-11 23:08:22.874058 UTC
# Is deprecated: yes
# Fixed port ID: 435
# Full name:     uavcan.node.ExecuteCommand
# Version:       1.0
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import warnings as _warnings_


# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class ExecuteCommand_1_0(_dsdl_.FixedPortServiceObject):
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request(_dsdl_.CompositeObject):
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        COMMAND_RESTART:                 int = 65535
        COMMAND_POWER_OFF:               int = 65534
        COMMAND_BEGIN_SOFTWARE_UPDATE:   int = 65533
        COMMAND_FACTORY_RESET:           int = 65532
        COMMAND_EMERGENCY_STOP:          int = 65531
        COMMAND_STORE_PERSISTENT_STATES: int = 65530

        def __init__(self,
                     command:   _ty_.Optional[_ty_.Union[int, _np_.uint16]] = None,
                     parameter: _ty_.Optional[_ty_.Union[_np_.ndarray, _ty_.List[int], bytes, bytearray, str]] = None) -> None:
            """
            uavcan.node.ExecuteCommand.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param command:   saturated uint16 command
            :param parameter: saturated uint8[<=112] parameter
            """
            _warnings_.warn('Data type uavcan.node.ExecuteCommand.Request.1.0 is deprecated', DeprecationWarning)

            self._command:   int
            self._parameter: _np_.ndarray

            self.command = command if command is not None else 0

            if parameter is None:
                self.parameter = _np_.array([], _np_.uint8)
            else:
                parameter = parameter.encode() if isinstance(parameter, str) else parameter  # Implicit string encoding
                if isinstance(parameter, (bytes, bytearray)) and len(parameter) <= 112:
                    # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                    # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                    self._parameter = _np_.frombuffer(parameter, _np_.uint8)
                elif isinstance(parameter, _np_.ndarray) and parameter.dtype == _np_.uint8 and parameter.ndim == 1 and parameter.size <= 112:
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._parameter = parameter
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    parameter = _np_.array(parameter, _np_.uint8).flatten()
                    if not parameter.size <= 112:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'parameter: invalid array length: not {parameter.size} <= 112')
                    self._parameter = parameter
                assert isinstance(self._parameter, _np_.ndarray)
                assert self._parameter.dtype == _np_.uint8
                assert self._parameter.ndim == 1
                assert len(self._parameter) <= 112

        @property
        def command(self) -> int:
            """
            saturated uint16 command
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._command

        @command.setter
        def command(self, x: _ty_.Union[int, _np_.uint16]) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 65535:
                self._command = x
            else:
                raise ValueError(f'command: value {x} is not in [0, 65535]')

        @property
        def parameter(self) -> _np_.ndarray:
            """
            saturated uint8[<=112] parameter
            DSDL does not support strings natively yet. To interpret this array as a string,
            use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
            .parameter.tobytes().decode()
            When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._parameter

        @parameter.setter
        def parameter(self, x: _ty_.Union[_np_.ndarray, _ty_.List[int], bytes, bytearray, str]) -> None:
            x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
            if isinstance(x, (bytes, bytearray)) and len(x) <= 112:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._parameter = _np_.frombuffer(x, _np_.uint8)
            elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 112:
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._parameter = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint8).flatten()
                if not x.size <= 112:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'parameter: invalid array length: not {x.size} <= 112')
                self._parameter = x
            assert isinstance(self._parameter, _np_.ndarray)
            assert self._parameter.dtype == _np_.uint8
            assert self._parameter.ndim == 1
            assert len(self._parameter) <= 112

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: ExecuteCommand_1_0.Request._SerializerTypeVar_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u16(max(min(self.command, 65535), 0))
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.parameter) <= 112, 'self.parameter: saturated uint8[<=112]'
            _ser_.add_aligned_u8(len(self.parameter))
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.parameter)
            _ser_.pad_to_alignment(8)
            assert 24 <= (_ser_.current_bit_length - _base_offset_) <= 920, \
                'Bad serialization of uavcan.node.ExecuteCommand.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: ExecuteCommand_1_0.Request._DeserializerTypeVar_) -> ExecuteCommand_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "command"
            _f0_ = _des_.fetch_aligned_u16()
            # Temporary _f1_ holds the value of "parameter"
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len0_ = _des_.fetch_aligned_u8()
            assert _len0_ >= 0
            if _len0_ > 112:
                raise _des_.FormatError(f'Variable array length prefix {_len0_} > 112')
            _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len0_)
            assert len(_f1_) <= 112, 'saturated uint8[<=112]'
            self = ExecuteCommand_1_0.Request(
                command=_f0_,
                parameter=_f1_)
            _des_.pad_to_alignment(8)
            assert 24 <= (_des_.consumed_bit_length - _base_offset_) <= 920, \
                'Bad deserialization of uavcan.node.ExecuteCommand.Request.1.0'
            assert isinstance(self, ExecuteCommand_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'command=%s' % self.command,
                'parameter=%s' % repr(bytes(self.parameter))[1:],
            ])
            return f'uavcan.node.ExecuteCommand.Request.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 435
        _EXTENT_BYTES_ = 300

        _MODEL_: _pydsdl_.DelimitedType = _dsdl_.CompositeObject._restore_constant_(
            'ABzY8W}=N@0{`t>O>EpomKND|EYo%@$FU<%#&N}QoYsuglK(YvCSzHaVxy)cK~fUWP6C?UtZq_flMH|K6JP<)VHY|OSYn3*<T98X'
            'bIjgy46v6RgFWRKV1b<gdzc&s*c|q-?^TiPZmAVpj_qJ}Y{0GV;;UEh=X<Z->#DxD=MU4D2gJYRl)qtyrc={H9@vIse`wSlUeg<1'
            '+xJ2{;#qR&26yZ>yfv3Me4hP28~I)Kk6AT&Mz>v;2bndH99oKkxDmwx?<Lu*yG9#WoQ{pvhT+y+&*Zh4b>4_0KJB&JhHKUq`3Er%'
            'qbwQJS9uWHo{Jp!y_3KHeMS{J@Xy)rvgCknL{VVZVRD$g5A1i4y`;*Ly|XrV%#J{sZW@uHM=0e^)BOOowO4`S=-X~+w_I-CawFd2'
            'L9ccP^tv7C4tHCTmC+$!-Y~*QZ-bJVbs{;wP%y%2wP|?9@DXS<@K4!dmOQVA5m>+o%x*@Taoy6AeGO@zEZL)*UL#BXXDO#8e!#~}'
            '-n2n1l2e7m2skk!5?P!?o=?1{cpDgQi<4?WUFVLsHd52x;jZZgApw^V`3&ZR2!Ro7jFMIHbS(6F!*1G*&KkBWnAW{0^4i2Vf@sS+'
            'piU6kZi_SnAo!36Ub$EwcA;fB4spGR#33iP$=wJD!0p7Sd#jvWIDh5xm0AYoI3^8l4JR+|;PD_ZHnQY}cMKSXkzWf_PT^>;%MR(>'
            ';cZw+Lcn@4=ll{Kv`$&CSZBcc$$s#oZ#3*^Bcp!uT<#dXiBRf0?`5i>L*?u}dff@L<ZK~n$F(4IwDohA9K3EvQr;!_m`j>ebkENc'
            'vJ;bVqh0qL8*p)y@wNwch#*+zeI6K*7j(yH!?Ga&tY0O^raiY|MBMF5ib^A8z+DV2pg%kpI}QM18|5?ls^P>u`<JXr2h*@_P36Y8'
            '0kd9ML?|qBpGWpiBHh*7#yXf5Cj43qTJr@jVZXNRLWtlSAY=C`$v%v!*fDTERgiWdrE31SBK|^>P*b`mAKP1w(F)y@(r4sn72ogc'
            'c}DlrXHq(t&)dK48QlkRQLUU0Bk=h^Upl&<YAHP^pAF(#hjyf+2k60+KHI|=Mq%vm_s*e*=(8yu%GXHgk^559!*nR6&uv=?p1}Cg'
            '2bxch(C1S6yrkU&&ky3<V-Gx+9;MHx^mtzx;3+(NVOPB9F?u|u!-b_mmJ_?4PhX(JDgDWgG64lVfAOLC(i8M2Dg9}Wz2GVEJNeN3'
            '=!^8HDShdC<pnCBIrW3qpeN}|DJ7+CQR<g}Fh_cdl9Zm7e8~67kE_4(NY<k-)6*$EQ>@wL2ei_wk8BP43O$q3v-kB3%pgDww68tV'
            'wdt$$Y)Y$zp1IFP9{C#dHCj#S&mLG$m;v-Ze=Ks)5&E-~j&^)|26$Gx{X6#9)}=qEqbaTJ$__9K=8Qj9ndlg;rF5c$gQ`TrxyQaL'
            '9j6m1J-=&<z)YBT;fcsc&(ZTKy|^7QqriKjK+UBmCJVhlFQ)YJL)i>w!`v%RR91S4UQX#`FS;fWU%z<ba?mSuGNrFSwC#Wc%)k1h'
            '$W4DiUr*^9JLB*otTBmL{N;}(AH7Q7Na>qD$iBb@c>L-|)q(z!zM0Z%+b|2>kD*=X>%QTNZy5vy8&K&W8&v5K8&c^o8&)Y{M5R?$'
            'Rp|tqQ0XL_ROvN#O{F*4O_eUN1(n`rw^e$F-BGE<ES37qSLr%iSLr==Po<k|Q>7_ORr(S8NTnaMk5&2!`$VOmvQJg|8T(A7pR><Z'
            '`UU$!rC+iyRr(eCN~K@3uT}aD`$nbTvTs%T9s5pY0}30cut9|lR@jijhAM1WVZ#+h6h<nns<3K>O(<-l!X_0qSz*@{cCEs0D(q&3'
            'EhucE!fq?<c7@$h*qsWq6lPVJuQ0#D))ls1VfPg1wb-V@QiXk_u#Xk?iNZcr*k=m+Twz}*>`R4xrLeCR_Km{6RoHh*8rM1Wf4_w$'
            '_&v5+vEKii>CXnSE`QAZ*&s^%ci*33H9GLLKYJ|wnXv66@6X8na{goJ&q%Ky{@?azq|;OX-SlUu^BLjYr~O&cpGh1%?a%u6XT6Ad'
            '+Mn&VKP%8RA@TLJKYPgjOzuig`?Dv}pP{W~MU(eu)}LUwrzOLNY<Npch7H-|1GHq=kgfmiwq%=?U3F!6kY;Jge%}a;HjnU-{%rCe'
            'QzVQ6Jf1CwNf`USV{?;4o;b+O4`*v+89p?<plw71J`>voYCqtSI6NeFSWuSdx-|`_6bIU!Q(n_6k9Z>s=802OQng#I7jR-nBcp_`'
            'H@Gj(jU%zD<9KWE>2-~eF)}^R*wow&{rb#Xx90Sv`Pt=nrxs`Qw-;_qEzjWL@X=&&+H-N?^7OQ74R@W;4wWanV3NZHzr~rQ<*CJG'
            'G|at4UiUnCcrI=zXmehK;)3#_*Y2lP+t?spApW3s0skPj@dO^;i9>KaEB68uER2RV?sCGLP2PyE5?*W7MoH6XL|(9g<UFcn)_iiZ'
            'IO^r=VCN9OmFT&OFt{j8Z#adLFlT==06s7p!t>euJv>kLUcPkc!leukr3DoJ>wacAQkZ37{@s~HeSUTp4f796Rvdu`*WA)JS4lGt'
            ';6p%+MgznoYj%E!U+2X4K<>K3N$f_pBj)(t8qk8@qc{*(5RArM0;+-d)?acxtiMWuFYZF%li!aE>+J16Y6An;c`LuP5PHpM4KGQ='
            'zG;AS{lF9A$06b_zn;>x9bQ}HhQNOZ<KX7IJQNVl?>n3>Bj|JvXmPbd#y}^!8lD>&wi`-I7?D+knakHY64`B|1+a&;@iCYY4eoe`'
            'iRRjn((_;y_=#&3B1|D>-AI$dN8NFUly-yn(P+LdxJX!wQ1ryvJjQdlX82Odz;i&=Tur$QCIGD?MNQM*_F+!IMbyGOLESOeXt&5!'
            'X>UFvfx_|X0NQ`e;sQl>gy1NFBMgxHOxwX{HFB#dwSbu>=WVc)-7Z*+cIPp<D3~<hD-eAg2fz!STX<6ALExdIOdgWrnoJHEh(gda'
            'L{%C+dI~ymyMa_?IA5Q-p+h=Zo*{O#3>A?j;~)SNIvbkjj+t?^A+o6fdDk?#E7NKamu9r1kYE(A0(THd*whVe$Ri+D?1n}Y^g|Az'
            '2TF|8G_Zu>ZpAcAGn@dNz5#P!?wYY7t&;nKgq9ZrW{tWR$gEe)MAk(H6P7B#iZ~k8V%I^cZdURN5opoITSPgwU<J7=fYbulwwx3~'
            'T;xE{-B-w2=ZNGE@JBUp!kT3_ELZ_=2j$cdWOB2T&N0c-+tbrCOG`p>3^&`2xme2s1-IZv6S(1+rvr2m@dN~6nkl>);?=5#6Pra;'
            '1@dYdFF5sDQD6(UL`ZDl(JnzWfes^*f=GP>!ws9TSYc@hY};M+?mln;!%98}o~E<Wm0t0&hStsbBTkyJ12k3N;b^&lH}hS{!pzc$'
            '@%EF9df4BkBk)cf!HZ2|s4X^TSML5u2RMOk0I?Z|kg5Q7+PjwYVpn1XDWn&reaya)gWXOr!aH)LDmB3Lc^U^!W8`(;6uij+h;`6<'
            'L<0rb{EeBdiM~b_9!Sl;T>EMZ%H0xR11NYc*ZvUkhDK_8A(R6f0Ec$I>siLC$XI0*<KlJz$O2wY;mHt5Ak*Rs{k9^lnunDrH3Su8'
            'f|AIBtrgR=kER8&Ak)bkY-nL4EJ900i7S~{cFP(wRt?)R>b7G;*2(2Y*D<>R7=%!PRPW$zJE0ve)qy)moX3vTsA&gnA&n?_xTFa2'
            'q9GTTIm_&b#CgsuCut&KiJXFx@^+n@VsC?*OGG>D5{452Kw4HFlAvzj84Ziei;d;>0Q#<R#~Fbwz?E{N-lN)D3CDii(V4O9f&nEa'
            '1^6JGAo~H~s%^+o@Bwbb{h^ZMx6ZYGFhs!|4;*BK`4!16i;K1SDyIA<W*%wXv4A@mDqT5WLw(C#qs-qmG7DJc>jrv%wAf{~<ozZ%'
            '9GSW1Rv|zkEYa{&4+KZGGA#?E^wq7ihf0gp@&GZM(AyRzHs->1FT^nFqtf~Yb{q{EnzF>kO2O<_C<kIE$}s$Wqi5?WZ3m^6Are?M'
            'jA6UTJ%H{TyLF?eWb$gHFinZ)uG$Ohvk}0xwgZf0PZXi68hM3;n;j-zS$GqumI!1@+^@@Z8&G7Gg+tLR$wbqy1ir9~68KnA0?$rO'
            'FV8Rj23wjL(a`++qTH1VL%b&Hh^F0&^LkHI;d!zwS`nyfjM#|^XN9DS!CrJWc~t-j<VMVksj=JO0amz>VTyvTs|5;+*^sGP+~tAY'
            'khv0;<Y8HbIDqdE6JMjNf$D3W^SiLl@xnSYY-aJTnYroTK!rBHfadwvX|ZK=7g}v7B5}udpi;uzih5wRg?TF~`k7objDXp^3F?&4'
            'vK16r0LHgBLmj&mwJF#~W=~+)Pup|5(DqcJE$9f5yD+o3bZcpOW^P%QrAyclO{)U~J#7tiCgR$DCt~un9>`o;B=TPDblMwn4OkY9'
            'GHv^KXCF2Ym?P{KYDK>T)$ghY@rr?l3qaJ>$egIU#m)6jVF!|7NN!_Aj5zXei*5ihc*(0n;x4~55PK3pNb7Dyu*kx<wg5CPLPUy?'
            '<xU^T+PsaC(6bUI6qjRuH3CS(H$hIwB%@-Z)m)(gy512HCBEQ*sF0mHY`mkSw~iGQU0=Txy9zd!(4)O|pD58p&B%M&t)8zMxEsbn'
            'R~;@?#ms|FHOn2S^tb8p(0wiHR23cNwbBI*o_hre`a*T0gep&tcKu32uW!g-fFNXFwT@f=X;rQNw*GAWul3!^K4oBFrGhWd;mfo5'
            'auQ!o;7b)>&cI8Y9MDaUl{u#SY%_UQZ`$kJ)Nwb`Z8Muoj_9EmL;BD$k?WYqv*d$u3p_Lqb`8b>7~F2T<8o_XJvRpRo)fQ|^|7_U'
            '21}3oaUJ#~J>acaY$}~!iG=y2aWvQX#S53V{(R+JZK5VgGEm(zLRcT8M$gN?Y!fohzuoEywR|@!A}-GYL^Pt1iO}FZbrs|y;UMf!'
            'w*2y=rcEKNw|zl{QRVp(hgXSR<ItsI3DAlGe1I+)Yydp`22d745H0ct8Gvc<@}zZDdil+s3;u@}3=<oqZ5R9DX@_oBPQ8UcB`8N%'
            '-T-%&B;8m4htjZ~41(nZ>x?Qf-YOZg-h=<|1JR%6VBosEYcg!T$3Ci*!z&b+(!sdTBl#_;b-+4k4OvG}l;Z%uKLhkCCE!jJFykxZ'
            '@cKh=x^fO)H&@QX>)gr(9KMJzmvGcNyK))+Ci`^0j!7+JclIa80oU@ERe^4CtTDFzx`aTIzao=-Uw?Glx!a(m_jeh~`MY=7sM7aW'
            '7uIj*z;<``qwR{@HlZ-0FgiZG*XJQlt^FS^pUz57HUIz'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response(_dsdl_.CompositeObject):
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        STATUS_SUCCESS:        int = 0
        STATUS_FAILURE:        int = 1
        STATUS_NOT_AUTHORIZED: int = 2
        STATUS_BAD_COMMAND:    int = 3
        STATUS_BAD_PARAMETER:  int = 4
        STATUS_BAD_STATE:      int = 5
        STATUS_INTERNAL_ERROR: int = 6

        def __init__(self,
                     status: _ty_.Optional[_ty_.Union[int, _np_.uint8]] = None) -> None:
            """
            uavcan.node.ExecuteCommand.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param status: saturated uint8 status
            """
            _warnings_.warn('Data type uavcan.node.ExecuteCommand.Response.1.0 is deprecated', DeprecationWarning)

            self._status: int

            self.status = status if status is not None else 0

        @property
        def status(self) -> int:
            """
            saturated uint8 status
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._status

        @status.setter
        def status(self, x: _ty_.Union[int, _np_.uint8]) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 255:
                self._status = x
            else:
                raise ValueError(f'status: value {x} is not in [0, 255]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: ExecuteCommand_1_0.Response._SerializerTypeVar_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u8(max(min(self.status, 255), 0))
            _ser_.pad_to_alignment(8)
            assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 8, \
                'Bad serialization of uavcan.node.ExecuteCommand.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: ExecuteCommand_1_0.Response._DeserializerTypeVar_) -> ExecuteCommand_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f2_ holds the value of "status"
            _f2_ = _des_.fetch_aligned_u8()
            self = ExecuteCommand_1_0.Response(
                status=_f2_)
            _des_.pad_to_alignment(8)
            assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 8, \
                'Bad deserialization of uavcan.node.ExecuteCommand.Response.1.0'
            assert isinstance(self, ExecuteCommand_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'status=%s' % self.status,
            ])
            return f'uavcan.node.ExecuteCommand.Response.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 435
        _EXTENT_BYTES_ = 48

        _MODEL_: _pydsdl_.DelimitedType = _dsdl_.CompositeObject._restore_constant_(
            'ABzY8W}=N@0{@*>>u(cB5KmMdCOit|(U)4TqD6p&9U7=AwNh&whejq2vK>BDLaV*Iac0H&?%0QuRHA~mpj6rlRJIad`ua~hd*>vM'
            'Arh&-c<*+1<~P6j&CESI@P|G!Rs8Jvd?QwIQe_IH;EDKwhY3_!lnwGs2@TF3pNB*YXc_l5a&Rx)<;U)!yJQbBk)|LWPTAvKEls42'
            'gxyCDvXl?V#0A5L5l^dW7DKhU4w2E&$OZ$R#?=m}JWCaws<0tQC9>3;JbZVwe&Jfvt*NK(v9m`R*IJ5@ZYy_>?C$}7`;@Z>7X&2n'
            '4x$+rbIqCdF!#EiOCPQn(uvb6sS>Lx#EYqhRgk;GJIX?#Spw;*M%Sv4@rWzU1{9^k_wBhmTZa6#YJ>Kc{1!zt^~80YJ;RhH3b>5N'
            '4Q-kbXY3)`(ndLZfW=wl><2xBK!P%f4zhlri>C($l&(6uaN1TH#3Gr~+xYN3{BX4TxK+XPcmY2xji2cD>b;dN>#j5!&2HD>MH_TA'
            'mz3imlL3?&iUVb$2$brZB-wD3@F7nOvGUOtZ?K*dB%h{TtW`Q((>tDQLBUyjq%V2o-%?1Gh0&V!?ewhkWT=pkU4B#G3-!g@E1jkX'
            '{#7G0NgSk^4wMhU2jJO>K?&*OF`C2-L9~4=^wjYPAtqorH$sSC+UaZifO2*OrM=u^^_AXt%bmsVoAVygg?UH?d5#SPItvmW-S;Wu'
            'Mq?&PWJTl?o<HA*=XXY)Z`S8oV|i(*-Y(qE^>#Et-lMX<0-=ha@2A;X>bWV1GI^f)Y)`_N+Xsv@V=(U2JN2bzui5cHzVSf3i^Q{#'
            'b4fiwgAAwxjOaItHr9m3B2x+yh{hmKg1WvBP$$Pg`DG!ITOLqkq=d8(iH5Bb@(n47GblOAL6U?=@~0$~r-;BkfZg~Xa#?H>OYQn?'
            '*6eha3%V9Ox{Q1m!Uz-=LPb7=vi=|@YN(q9JPk}rC0CNw=OUqo8)Q)t*(>0_*aipo^jPC$;YQh&J;=}S99HoPev4mY3vc0F>>$T`'
            'm>}XBDnl(U2CDIhd$DZV6Ra=RA!c4ZOvJ8jPcfAl83Ao1z;aFv%s!|gRa}j-ENlHt0(H<@IRS>(u8OpunDsckx+ZC+$Xaf~L_|!&'
            's!6<;od&H&mufyswd->?CP&A$>TI<<LY<l+SLEO4*!T0Hh`?<Uy;Hu0h6%Nui(74Lr`gg;J^AeHv718QE}pxv-A?UWEX$n@_A;V2'
            '24O~#5R@etWTQG?F7lem@v#}9ppk^X*|+cTI2P&ZD~IrRzuTs^%jL%8F3vu4ms*wQDx`^-mlkOHn2_Qeh|~`vTJUwhIP8ZJ@#^u<'
            '_;$_HVyL!FSjct;kK!>riKl3qk`%6x3~rGG?os*`;E!)25qz|XkK6bY{*1p6-}r=_!n&q3xTQza_8bYQ{CtoMfyeY$4BxRj38+p!'
            'X-#{%meukUe=Q@m_-u@jvoztn5YyK(Ymbz~k^ua-0lpj~D<HCVnR>Uw(^cp|4qEJ$ru!v{vvlF*1o4FN&o=%=@!{VOiD&<Q>bb&y'
            'iC0jg&3|6A>91D*13fHc6n_Z-00'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.node.ExecuteCommand.1.0()'


    _FIXED_PORT_ID_ = 435
    _MODEL_: _pydsdl_.ServiceType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8W}=N@0{`thOKcoRcI+8_Mk86GEbFt<O0Jc(_Ru0n)L*vjUD4!FBFaTFL&}yH30ghVHSDH(x_kS>kFf!`ha?QrKpNgj;L8FI'
        'um>G-aIlB?v@j9`Fmf_-^3g{Fy9Xg3#5n}WdsW>%9}Xo^mSk*J0#xj&epU7UpQ`G$ZGZDGZw-il(aY|t?(0@r^|@zimid8Jvv^sp'
        'J5AT|&49O}-E-VqGV6SP)#a^Uw1$4(`qNe^dO`L0PebkpYJmO5K=i@{x6CFC(YqmcsHSamPk_t?URV!8uV=FDs;xC)sgt3$RM+gX'
        '?dZH*S>g3C;NwoSso8qDDwk_T1$BvgzUkOF<IZ=J=U=p_LI?i5^>aX2)q=n?YcSYv{RvFJ35^+4E80G3a!YR`R8(~>&?IS_4R<}H'
        ')?5OJ1GjA7T(G%5We0qLd)?ISR%>RUTHIa;j20b)$?F>MtqDZ7j1$qJ*>oZtRvw3U3||371Ao@4wxX9*KL8GBp58gpdRQ~|MLX+~'
        'J*{Y)syp>o^xty{EO9+PqVt9cXpscUCz{8J7LdT;Bye2fG{mE)*$bSMQs^4DoaLc%@m+4~j^`5)36bw$JfPrd-s&(}5^qO*m)FgP'
        'S#Pgl+G5h069i6^xSALAtOMkDfoU(0h6ey2aL>sW>oc8iXqH86Cm^BEiK%lt000m>(Q3{TCl}6NxqPME0(Kmg3^$HP$2O6;=V`00'
        '=<vH5^g_=&f|X;~+pFE&;!Rj7(QcB=e2Nx~(?-b{0`5n<K#s0fH-ps{b)y#(!Ke*XrM}}{p$ZCAj^3u$EWZ`Kl49BxEg&8A{%%Ek'
        '-Zle??;QM0Fpcu6<F+EQ*(CmIv*uVP=*0oXn-1_H0ArbPxu*q=*J-15!vq5`CZdDmj$PLRZubR6q7l;LHkuZ|@0$)S3lw4l<PLR7'
        'vqIkb>sE;tV!vigCd`<EQHQIj3RUj%z}yU_yJ}Ng0oKBRKN6kBd^(rlU(>X~MDPK?*jhf?i8d8l8jhz5!VbhVm;B9(zu+WtG2NE*'
        'ZO{5>o^Ffj4*5HW&pW%`(d~3cObf}lT^rufoq!iDX5*m;e(&xJM|aU;O!vrl1zhWeP2uQnx+kW4yXJ*n=-c<eG4utxH>QKh8Zq7f'
        'P-wc34#xDw4J*ML=s)mC<LQ3-VoYC>u-oAM9vpk{k;l>l^re^{>Wc%sg?ERyG#5Qc55@FI%4xvmds`k)57Q$tJ-R7Q00HlhJ=VPR'
        'd-P~bzu(0#cnk9#f9(0_G5Y<Oo_HX>00l5Ff2%d<ae5-AB;ze&{ey2kBYl~Yn4XmLkO$$9tDkxz>(L+3lQBJ=uGt|6<kAnH*c$W{'
        'Jss0m9x53aK>!+HUwxu$(;w1TVp>Y+Ok_6n#Mhv&(o#%cdt^Fc1i+tpDtOQ#`dUnf+p;|kbCx>gJMz@lrDy1HOv_v11B`+(XP+ug'
        'bcB{;I@;EQlGKEAPkmK-mX5~s{FXTaBVpWyXM!I+N6*Lf;zo@bhPg*mt-18faG@9I#h6}xES|w=7<=WJ;z}>k%Q3y$tzDz2U#~xN'
        'Jm?jAHKuPoHt%2t7=P_M!JEEL--zj(o9p34SmP?{;#=Pte)JlBGp0ZKR{VuoV2&Sur!>&F=#OH0eS^+|^g}4u`HHLAVwXWcuz?&c'
        'utJUwvcViZ!j9x9VI)UOtdygpY&1u&va30Ion6n-o9t$e&a&AYz0Gdt=pA+^M-67=sLR|OU12LZy2jRWbe*l|Xw2dq{fK>(qaU-6'
        'bMzj&m!qGsPjd8A_GylO#y-o@&)MfW`UU$UN55oW=IB@Ks~r8BeVwEC+5H^-hJBM`0}30+vx343c{Zr9!8|*nup@a!6h`u_q_9$+'
        'jVf$3&#o%$YMxzJ*!4WSsj!=QHmk7NJiD#1+j(|JVR!P(P?(WtuEN|rTT$3bo~<cRYq52O#R~gKVIM2(p29v+*ry8nOktlZ><fi`'
        'sj#mU_O-(9E9@I34r?6hzdKL_YivDl)P8U3vjXPjPq{uTAjW_2^%-WP1JCQTr&6B@-ahgAj6BTeKZW{?bj#uYZGA@CHT54%eTFoj'
        '7SerQpQZJg)Pv{sS^xU1TVtNrXIrh$QtcX*`t`g%d(8SwMy2QV*|Vt6kk>M!N$NA>SJ2&6l3_u1q^Bgqg6!%elw??tt^EF$Wb64Y'
        'Rb_aPX6%c0xtgand4PxXXQF=_BYxoF@od&j{LpnRlj|gK#6fOyI9n$3@T1{)O)Vhso0v90yB-h3;UO{o6f!&4Ef;Y}dZ67t<<*_+'
        'h&M1`oH#`#C3C@cJWkADXqfPoI(NmnaUfQ;EN2;hy-_4&gpAKHHa0z>zFoO7HLcFgOwPYIR;{SFW+%qxD|k43Br1$MHZGi<o|cT`'
        '9VfJd*~u=jWM4X8wK6w9R-H%2tW|l<apd8-xS>#-b^=5fi1(dlKdPGADsepV2dTp=6DFR(!;?4!$Fp+B(}BatSnVz+ywTwG;2PoO'
        'h4L_IX!XGHRuP;B<(4rY9Z!#X`3msa$6bl8s|bavV7+FgM8cR|4G-plULW31CeQFb+J5=cr3;r@cqlDY;kOTC%l?!tvor5is_M+-'
        'Br@hFb4D0|1efiMH`hob^x%g_w0a%TB+F)Uh+pHxbpY?0#Yt!frX|L>&N9G)+=I{)R}i%NT>_*5`o@1IbQu355x%$ugpWU1FN`y{'
        'e_0$Dc$+UImlk}d5iH{+iO|(G5U%Sv0{zfOy-TjAG)#+^t6UTM-_~&u^Ih%>6;AFuoXjlfWTMdGYK63cwsqAVJJ3wqmz>Z7BQ-Od'
        'FSju=o7w`XJ*<tdfsM#;%h7aX*Q&&xdrL5%xK<&|6l~TGiW2#t)9!qEr>74^Gc_@bRBK_1jyRh~d-j(#S7PZo7Lb~dDVIS9P;6sS'
        'E*5XOFvjD;YT-#hx7jt^iE>Hun-57v;dpfb`M+#%p+#nZ%8@CKU_c_X;wCaHlc|QJ0!HebH-S%PGo50%(~rqTfu$Z_1ncA20a9@6'
        'RFXyRc@7Fn=RQfV$s{TRRtR+ZNJ_nnP5~!wH;|Gv=eNfuRB$Kr6=F6rQxRS=^gLjpwOVxS5j_l6g*Vl}@9H|YrCasFjE!dC6SU$b'
        'm>m!jJhgoj{0N{G+P>BR`fvu{0V0OVMc{;H_v$nZ(<~2!z6xVt?6S5hxsu3&_=XdL&T2KslU^?!iBqQ@OmHeyR@9^6VrW|k)j5^C'
        'LIhMa@fJ~{Td;zR3V^lHYf}#L!7dU-PsEqvS>ve5ZN(ohf)JJsvu?l&csnS81|yTfN(x6ObGOFFD|2%Kb2K;84!Ky%0RnsUrYQ7='
        'qo4LrM8pv)2*Y$CO&_mT)vZuZttz<*$J3d*xhQlCLLxXekZ1=YMWG#9AQ6%DdYbJwV6l|bVA!U;<lKE^1BR7c4s+_(YKMEp*G1%R'
        'GC%4`BeVdf<XRj#=kZ1og$(p8^$>4ANvntWE(L*i;s{=B5?xIZm~9#T5f1bO!T{=K=!2^QwJW}7NGWzWR=`3^QSwLct8x(S#6);U'
        'j+7(?=sr(k$4Ruj&YOZaIVfTcs2(Z;0c>WX((CBUWcHEB>^o~;YJs>Zp=_WE&Vp@zfcl0^YC1lo1FN78%_Qm>+LG{CnHA&WrU#k@'
        'b6Ke*eFOndi!1aCMa5ELRwC69P~ZtNAOk`xx@Q+z3uu9-lQ-Cq!<wI(mb4OEPGXn~#)!70nU+>FEfc&>f;WnenRU=XFcon17T&fK'
        ')ZtQXbq9<S+mRGCOs^@h5eW~M5I$Zs<l-`C<{c3@@p;*xqHtKkry!=hS>w8hZIE*bYlkSISpg`>f{~ackn1^G-Qe<KV-_BO-eqoC'
        'Ll6RNi8s<cTwKo7vES?{%+R)hfl?=h@_{*l_XEHsQ<J?Q0}RCdRVC5i8ZY)!LqyDSKtP(GT#@WqT&&HP(B(JK^GNQFc-%r$>G1hQ'
        'q&JHing1@6NzhfkqM`JM(<sy9_ZuK^oXpmHkpO})MZ;fRDmYxs+_GRwU)tI+RC27G7>H*1&IT(n(HAzmRSc~@$hfaz#Zi~0DN}6B'
        '6!cDl5=CrV8JfSVb%maccaUmn!hx0i5W+<w0TkcJ)I^%eB-u#HnoOTNaxcu!hCr{2o2Zeji2@W=J;{(T*rDT<i8q04iGZiXc%7|V'
        'ha@XY9MW1zI+}hd@P#d;zz5S5cyerfex~|9mNXSn(EM{%Mx~SyuZldPVJ?J8z9+Kq#95}L2xK){Xa%XTd{RPVPb-@wD*y*F5%P3s'
        'XxF)i87_F3G@<J#f&6qdc&Y_%bI+_xUkOWcKg&Wa&~G0dU%jJ%>dT$;Tj0*2lsgqxsotnekG~HY+RQAn=fiOkGCC8jCM1y<u`S4y'
        '(6=HTm~Elo3etKeK@BZnGAV-EDYPsFg%^PSjm1!#FKKQH{E^-hChSM;xh+upa!M`G2$nlrsm@K!%~z)9Wm-Ci1<`nJV4$n4fyzW&'
        '+izP;;?_OsOH)VQtvl`VMqC4yNuzYzF5cOP00LtK-~3`)??Cpu<bb`Rq2U5xb!9RwvTkv6y`9(rW@wTdrXpGxI2fYq01Q%cYT&rD'
        'O#=~=K!u8(g$O2D_-G1+#zly55i;HBgISX|(Gt2=LWg2=^skx+ZulnP37%wF1lpo4C_vF$!lJ|m2Uvxy)FJQ=lkPlLKy+-sq)`Qn'
        'OQ_LqJj6<hB4^}X<yO~L1GoLq>&U|espxr7sCpKGGI{F`_w84Mc2?0QzL<%i&J(F1KwniI%~X{~2RgpeP;0C53lLP<*NkJv*T#r('
        '-}v34q6`ce|GT&c{wx--IgHH#Y))cx0-F(RhM)<f-Kx$pIY*D*T95Xs4ReL-Dh4Fg)LYZhe${tE@E|Jsaut1fEBfhK1B7%ISnHhy'
        '-QebeeO5;IrE?>Y@>$`EUK?5VOknm|H>^QeQa!#9in!ALP{dCLokfnFy?EhL?-wlR%A;io(gNxY&4=~TaMUCNY^{US`G=`4YfA!B'
        'YIKPsAfgrpXM{ZOO0B>h2^nFD()000xj2TJy<v|E4a;$*DqbUInM0w9S-?UF`UeUo?G1DfHvwfX1O_9&$pEzmLBC~Omx3Pey5qlZ'
        'R@1RY+HkiY-nQYW96F6(6J))MV<659r1SRwVC>hT0&q@D-J(i}7fS{W4gS{v=vULwaYJ4=Ibvw+qkPuAI17`~LfGe(+z2%Wjs3<!'
        ';}D{93^ed}pn8Q&;ZCG##uqO_`z=*<@iMgQi&vnXUc8FkuVeED_8MmvufgAFr^;8*wYAutUC|*>ZTWqbry3kHjSb(J5ODQxN>|@k'
        'B%Q48<SFU?I^+H1>5tj4()Zg7<IXg&@6Ik{UwY@p7km_a$Cqn;UW(5)_NwWANrL{)WVNEPCwbZzoqFJRU~+h?Evut_!d{^>?CrqV'
        '5c(L@kIu_28%$x+uaaaMDLx_k?Zc+pi-GdioSM|}I3<~r;hu=pTSjV(AQ%ipk=^48mC*-B?7r(wj!nIDtBO08(Y0~m>d{7JrXcEb'
        'aMIkzBnorOI+l0!3`}I@SSRVdsGQpZDhCr(rf25Wv0L*uXR1>_sZ1b7rzW_Kn>f16`9zRIXB0xU<|Q8;^{#w=3oE~vtc?3-Nd|+<'
        'UYPINeCbG-km$QMZb&<xWK`<AdeOMB1vFmjKx1~SI>svVl`10gV{xXDo{@BH?8<s7iQDb1GM`&=n=$=*uLr4%TR>{C11XWjAwoCi'
        'JMuD_n>sz=T(HH(4Y{DVI&UWpy@*|U40V~B1};sHy`xsD)fvIANyM&WS6QYmVw*&m4Hp$v7>GSfo3FT%Sy;DX*5cF!WgC#Y+|Dji'
        '554#SI@Kj?*0A{*Hh+c9UtsgM*nEi1-(mAhZ2lgbd)WLVHowN^pRoDO!`*f?&_5V%9?sCAcE+Uw1hPU;SXvA)w4~lnQuDKnh7U8$'
        '?`8P@rZY-CV;(I2EB<&F8n&h^zK5tky$D4|9}u9{lm`T;kCpxb3KaL~=Fz8b&?(?|xQQETB@F2N8g<b{ChUs}UKYAiptg|y9l3TN'
        'oBzV*KYAF=ey#Md`Y)3#A*_}E4~1fv3(!3P00'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
