# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/user/foreign/uavcanv1-influxdb-writer/public_regulated_data_types/uavcan/si/unit/length/Vector3.1.0.uavcan
#
# Generated at:  2021-11-11 23:08:23.197581 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.si.unit.length.Vector3
# Version:       1.0
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Vector3_1_0(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 meter: _ty_.Optional[_ty_.Union[_np_.ndarray, _ty_.List[float]]] = None) -> None:
        """
        uavcan.si.unit.length.Vector3.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param meter: saturated float32[3] meter
        """
        self._meter: _np_.ndarray

        if meter is None:
            self.meter = _np_.zeros(3, _np_.float32)
        else:
            if isinstance(meter, _np_.ndarray) and meter.dtype == _np_.float32 and meter.ndim == 1 and meter.size == 3:
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._meter = meter
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                meter = _np_.array(meter, _np_.float32).flatten()
                if not meter.size == 3:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'meter: invalid array length: not {meter.size} == 3')
                self._meter = meter
            assert isinstance(self._meter, _np_.ndarray)
            assert self._meter.dtype == _np_.float32
            assert self._meter.ndim == 1
            assert len(self._meter) == 3

    @property
    def meter(self) -> _np_.ndarray:
        """
        saturated float32[3] meter
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._meter

    @meter.setter
    def meter(self, x: _ty_.Union[_np_.ndarray, _ty_.List[float]]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.float32 and x.ndim == 1 and x.size == 3:
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._meter = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.float32).flatten()
            if not x.size == 3:  # Length cannot be checked before casting and flattening
                raise ValueError(f'meter: invalid array length: not {x.size} == 3')
            self._meter = x
        assert isinstance(self._meter, _np_.ndarray)
        assert self._meter.dtype == _np_.float32
        assert self._meter.ndim == 1
        assert len(self._meter) == 3

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Vector3_1_0._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        assert len(self.meter) == 3, 'self.meter: saturated float32[3]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.meter)
        _ser_.pad_to_alignment(8)
        assert 96 <= (_ser_.current_bit_length - _base_offset_) <= 96, \
            'Bad serialization of uavcan.si.unit.length.Vector3.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Vector3_1_0._DeserializerTypeVar_) -> Vector3_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "meter"
        _f0_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float32, 3)
        assert len(_f0_) == 3, 'saturated float32[3]'
        self = Vector3_1_0(
            meter=_f0_)
        _des_.pad_to_alignment(8)
        assert 96 <= (_des_.consumed_bit_length - _base_offset_) <= 96, \
            'Bad deserialization of uavcan.si.unit.length.Vector3.1.0'
        assert isinstance(self, Vector3_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'meter=%s' % _np_.array2string(self.meter, separator=',', edgeitems=10, threshold=1024, max_line_width=10240000),
        ])
        return f'uavcan.si.unit.length.Vector3.1.0({_o_0_})'

    _EXTENT_BYTES_ = 12

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8XQGW^0{?YX-%r#)5I*EiKtzKWA2ddu6d!2sM-Pf`YI2$sP6CEEvuxYB+l~E|-R*g2LLv_uNj8y$_5XExJv>0KNt4~q%s1bB'
        'Gt+O?-)Ggz_|ea@Q7FU6A`%3r5&ug42rLq$ah6K1!044jCGtS!0zQs1Fc;?KsW~wlx<(Qjqy1@42LVki$*nx$%8DTAD`p)*pi<E?'
        'dXWr3NS-E!RrJEq<a}YgIj{1=oEp7Ms8WLaxdLfEnOT(nIvHK-aEQVwl{+M)iV{`u(@$oE3qeOlKkV=!gu7#ouZvIDi&`NNK@5qS'
        'fX(2N2_AFB2k5cXiBhVrqbw7jD^dz!ymjOkP^n0qhG5uZ{b>I(ya==2qHV7*p(d5@<^V|&sb~^X5ncuQi8wLsqsDnyB<=|sDAZD-'
        '#+}I-G4zX;Q*XM>mb10ha@$SUZSS~^#&+FlxGl$Z+KsK9X4`S<rpT51dI{NOG~jAvym?(EeuRk6FAJX%Kn>K*yU};wa8=5Ah}Ve('
        'dY+`2(d)B7<S6#jhzCZm?LnNPtOfZG83>9)GZpeS2^hytv$lS402wI$f4^JgGjeCI(C>aXk0L5YH=Ph`K%*SYFSFsTpGzMruacN2'
        '#yc(!bXXh~iYDa|#Q<-v@T{CmlpTf{O~!NE&HW;j)pRWe1;Su#m|`Inl#=STE3-`eQMn=~hV8OdiDMB$CLo{+LUX3?kzO&2Buj-N'
        'JTzUsN@SXg0MHNt$tX5mXEsY?uyY(hyO#>!{lqReZqV4|NiWKWp}+Y>;I0Zg%Y9Up2<T%Cm}R;bauQ@qZWn86m+i18Yic#Dx>b5$'
        'PY9zD(~DvcFz<i|V9wYc>oSWq#%eN$ZI{}YqVLl%<VpXZ&Y;!BKR{NRjkk!>b-ZKt4&V0(<4yFm{s2cdIF*zH000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
