#
# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2021-11-11 23:08:23.183557 UTC
# Namespace:     uavcan.si.sample.force
#

from uavcan.si.sample.force.Scalar_1_0 import Scalar_1_0 as Scalar_1_0
from uavcan.si.sample.force.Vector3_1_0 import Vector3_1_0 as Vector3_1_0
