#
# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2021-11-11 23:08:23.002944 UTC
# Namespace:     uavcan.time
#

from uavcan.time.GetSynchronizationMasterInfo_0_1 import GetSynchronizationMasterInfo_0_1 as GetSynchronizationMasterInfo_0_1
from uavcan.time.Synchronization_1_0 import Synchronization_1_0 as Synchronization_1_0
from uavcan.time.SynchronizedTimestamp_1_0 import SynchronizedTimestamp_1_0 as SynchronizedTimestamp_1_0
from uavcan.time.TAIInfo_0_1 import TAIInfo_0_1 as TAIInfo_0_1
from uavcan.time.TimeSystem_0_1 import TimeSystem_0_1 as TimeSystem_0_1
