#
# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2021-11-11 23:08:23.096616 UTC
# Namespace:     uavcan.si
#

# There are no data types in this namespace. There may be data types in nested namespaces.
