#
# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2021-11-11 23:08:23.103834 UTC
# Namespace:     uavcan.si.sample.torque
#

from uavcan.si.sample.torque.Scalar_1_0 import Scalar_1_0 as Scalar_1_0
from uavcan.si.sample.torque.Vector3_1_0 import Vector3_1_0 as Vector3_1_0
