#
# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2021-11-11 23:08:23.202445 UTC
# Namespace:     uavcan.si.unit.angular_acceleration
#

from uavcan.si.unit.angular_acceleration.Scalar_1_0 import Scalar_1_0 as Scalar_1_0
from uavcan.si.unit.angular_acceleration.Vector3_1_0 import Vector3_1_0 as Vector3_1_0
