# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/user/foreign/uavcanv1-influxdb-writer/public_regulated_data_types/uavcan/file/408.Read.1.0.uavcan
#
# Generated at:  2021-11-11 23:08:23.074002 UTC
# Is deprecated: yes
# Fixed port ID: 408
# Full name:     uavcan.file.Read
# Version:       1.0
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import warnings as _warnings_
import uavcan.file


# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Read_1_0(_dsdl_.FixedPortServiceObject):
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request(_dsdl_.CompositeObject):
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     offset: _ty_.Optional[_ty_.Union[int, _np_.uint64]] = None,
                     path:   _ty_.Optional[uavcan.file.Path_1_0] = None) -> None:
            """
            uavcan.file.Read.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param offset: truncated uint40 offset
            :param path:   uavcan.file.Path.1.0 path
            """
            _warnings_.warn('Data type uavcan.file.Read.Request.1.0 is deprecated', DeprecationWarning)

            self._offset: int
            self._path:   uavcan.file.Path_1_0

            self.offset = offset if offset is not None else 0

            if path is None:
                self.path = uavcan.file.Path_1_0()
            elif isinstance(path, uavcan.file.Path_1_0):
                self.path = path
            else:
                raise ValueError(f'path: expected uavcan.file.Path_1_0 '
                                 f'got {type(path).__name__}')

        @property
        def offset(self) -> int:
            """
            truncated uint40 offset
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._offset

        @offset.setter
        def offset(self, x: _ty_.Union[int, _np_.uint64]) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 1099511627775:
                self._offset = x
            else:
                raise ValueError(f'offset: value {x} is not in [0, 1099511627775]')

        @property
        def path(self) -> uavcan.file.Path_1_0:
            """
            uavcan.file.Path.1.0 path
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._path

        @path.setter
        def path(self, x: uavcan.file.Path_1_0) -> None:
            if isinstance(x, uavcan.file.Path_1_0):
                self._path = x
            else:
                raise ValueError(f'path: expected uavcan.file.Path_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: Read_1_0.Request._SerializerTypeVar_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_unsigned(self.offset, 40)
            _ser_.pad_to_alignment(8)
            self.path._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 48 <= (_ser_.current_bit_length - _base_offset_) <= 944, \
                'Bad serialization of uavcan.file.Read.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: Read_1_0.Request._DeserializerTypeVar_) -> Read_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "offset"
            _f0_ = _des_.fetch_aligned_unsigned(40)
            # Temporary _f1_ holds the value of "path"
            _des_.pad_to_alignment(8)
            _f1_ = uavcan.file.Path_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Read_1_0.Request(
                offset=_f0_,
                path=_f1_)
            _des_.pad_to_alignment(8)
            assert 48 <= (_des_.consumed_bit_length - _base_offset_) <= 944, \
                'Bad deserialization of uavcan.file.Read.Request.1.0'
            assert isinstance(self, Read_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'offset=%s' % self.offset,
                'path=%s' % self.path,
            ])
            return f'uavcan.file.Read.Request.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 408
        _EXTENT_BYTES_ = 300

        _MODEL_: _pydsdl_.DelimitedType = _dsdl_.CompositeObject._restore_constant_(
            'ABzY8XQGW^0{^vGTaO$^6&_>9UbpRBaN-0-kjet~tTfweTLB{c!eVC=v);AY-CQ0(o$BtIsfxS1ny%`d9ZMhw3ABM0M5H4{2>t_4'
            '{64-@)pOaK;Dt!e_SEHEzH`oZPWST*Ul*_T+<(nm<s>y}7Dh%?if8H>k24WQiOx%Hlof4r?SaTtj>mLwQi}GgcIET-w{5?<7^$KV'
            'RV#bVwOw1)iLEPf^vDZQ!E=asqvrbwFT$aM>>a^V{O>olFt%-$qJ2>rr3;dC>7(xXt9J9;X77*f=WTN(;?`CwuB|ZbuOajdi)W|W'
            '=7kL<vUF}n5T)Gm$dYYmT`w#0QSIZz^$!c9MukWp7FLWzb=0RTQLJo~iDG1ByGg<mZfun6RJ8It&5b8hL3Ay=kG(D0B9H#i?zGLT'
            'k+Hl;d6g~-`l60y&|K8Rp%FmkLX_&HZF()1U-OFP8}d^36f`d{0{VnQfV?VSoMI+l0Z#LK&6{T+R#kk`Hm`rgv5J*P&XjdpJ?iqc'
            'NMs@xh4m21H#^DS+gy@w$+tIq<e2=yVI4P@fkw#_Whd=s*?hZmFB(!nPQCqofA2yRXQpj#PA#271EcNn-)(dC=gN9}ck#2cv^gK?'
            'vTfK|Ld+zOb*2F9^(~QW;9!w#k4sT;tE<J#PNYHt$@iPr?&~7qRurcmC3op$B??MSoPTM%&N5z2PMo|L?enY_?O)se=F*oYmJd4^'
            '9^uyOJG>Z)9Z?Fa&NAs~l=B0CiVJ&gQGPs?<?zc@(QfwW0mrtUpKmTvPSzR6(am#owD+Y!wu*z27p};*>sY{$1aU~W4$n)ma8OF@'
            'l4K;?h0-P1O?eAHuQyA8gi?40JEi8)px$#q#nsEZ?>$-HS>JoS<L=9ko9|A813M~V$dDt&x3uGs=Gjy_?pz*LJfT%&$kImljQ!?Y'
            '@BE~t+;fKJ|IL_SYyFex(R<tP?|sl&BkN9ueAb-5bLZ|%m}ssq&`uOjJdu&mr}DO}WFdbqe^-MHQUNz8L(=xJc@c?zAkwJRm5o%|'
            'Za1$)M%Ps$BC6EL0of#LQs-i=Mm4StbtS+xYrdZM@2sj~nAHbqygIHxxz$=($H>^I5+j5XTIN({x=U*$dW}dRyc6CI{UTC4lH5RJ'
            'MRf~R`zjIb7xLyOZ=dh=w!yt3Wh5pH))`4)W`ebxk&R3g2}mnts$d`PZM++@Jt>$jvI#>LtCSf5!IYs)8D_BuKgOUmW-@LhTV7ix'
            'u|^dm671IcSX^P17=q%N)$UfMwPmRSfDkodeOk+O;xd5gAsb7TNK%oCp#mYZc;fDnJEB?%gB<}-kT+f~tQLm#MK}uCau`A#yk`aJ'
            '=<b7f-EY(v5{@9~^UO+Jk0b;`QO+kUkyMT3yYsB3z6M=L`+Z<ZX~_B{L=^Bk5$VcL1IAX_x`(dR3Wtgj`N%!8fQhqA6;El+V-1y='
            'H$}jtvBE_@M>RZK;2bSTbt_ZB^PNum>5>BqB{)Lmbr)<;k<2xD0y~k~h=Os0i?-saSVdc6v9M!-Wtt3td8{&!yqBK}Q7)>V4g-ep'
            '4hY1tu8dtpqZA~uFbGzs)~D7?H;NEJM$HYn;PWigV?%#tH({YJELR1A!lzlL94RFtK;AgFe5{#<ekkJ=LQ1s*_v+%Q@u7guf^u=J'
            '+5Poxw()?0YI0%1R{l)h_vEl~gsNY9!qXHQPf#>=e}QSH^xN&`Qhk(K&tg;|59#&~<qi3F*{|iF4&|S>Wz&rQA1v|C?RWkBwZIhe'
            'FNa`-e=qfVwBz%0Sm_+lR_KzJDkv2`aZpZFQiK=AL!)BK?%E<J5NrUCXw(Uc&<yL0B?uZy<4(vP5bkc=K(w9-hT)HAhAE3scH;u&'
            '0o9*Cj8S*oy5gf0hFDjJWEW0Q%~XOX62&_~R}a|TlL~MygB2vGIHG1SwR^&ziAw*^T04yng&N7J{C1KlPy#E2NPR{Lo5)UvMM1dx'
            'IBlmjS)s>MfS^BdIZf(2cBYJXiJU;2aTPBqooOT-uo?n009@!|73gL@nZ3`>KvZ1eEPUu~)A460NKYT0I&V?h-GbtRK#Yks5pd6!'
            'zWk2y3l>u?Jm%s+8M`t-SutLgl}68oBTQ74t^(>7-~w3Xq<T{Zt^~=H1yiSoL|!83FxKgXzZ1gG2r&%<R-wh}L}$!D7lMwU{R<+1'
            'RCy|n(S2*;73wEGUtQ4PCF#Koq%eJ^!IZz8&)QY5yYFcxS0hPzW$MgMnZFCJj^|vH@|=%^FB0UACN_*aa|Z!%K^6M$l?wL`0kWck'
            '0j4^~1Wi4aNIP|<)OEq3CXOQo$*jeM?2!QG=yDV9&X`D<*h-90@{>ThdZXVk+A_(}1Udeo)4Fz(s*$ohV`K#<G9JvksX=^wbEjaY'
            'p8-+$>D1IPvGP3@JjiJ32~0h7V~r<!+B=c}2bhj&jAJ}Wbd`3UijEQgkd;%bPT0f{IArVw_QV0tORAMjxFW=6+(mL(5$Iv8isiu^'
            'f%$x3B=2&nFm*Mb61w=+C51zei%fH}E(~_-veZV*3w~PVWGL>}uK0F8SYN&SqaP2L(I=dC7v`Q1wa3gkI(CH~i(ol~WstBOvW;1Y'
            'U1HDUJec2uKMS7D#4JQ>zCDv1tPha^i|)-F8Z3e^?%0Q?bA|m_(0P*sz6CqF!f|IQMY;wXRQ{EH#Z@)PFnLP+z(<@qFU=vE7;WMP'
            'gqj$~z3_x=7tNuY*!+B@OG_Ct5(O2Zpq3%MYBJjdytX<=6?t(OLkdAH1#eaN9MZE?0SUXibCPxzQU=uaBzX-MW=9W5(AnxXW?B~V'
            '6WTmf$J2Rjex}0<rCldP4b(b48BMJr`+`}vcmO>~It0zMn{-*F=u*fY$NNgxCYua=(##S<<)wQE0zM88M-qO(aRA;69DyOXY2X?h'
            'x3}v=5QI0E)mgO2s0Cu6_-7r@xrRdBfhvG|4)LS~k`ELGgT4+-$&RP{%6Ot9Vs@_$T`@U($sVK>)iMBfd;?l{@cBU0d5lFM?LHfT'
            'yU`N6sWWr#dwrh3&l=Ufo;}Uiw*9eR(!2U;Cl_C=`}C6jO*h8%Wr}~(DNg>)zc=5;aQCnIa5p=BY~2ri@`}7FU-qA7Zpi)_W1swo'
            '8^`27@%rvE#<p9ZUT$vSJ=1@Lt0IZQ#Gm6IQ`qcd%ISD4`o8EVJNhx=SKU*zH8^+brv{m9!@W;0yUztni=PV|D75+fluf!C{s$U+'
            'diHq~000'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response(_dsdl_.CompositeObject):
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     error: _ty_.Optional[uavcan.file.Error_1_0] = None,
                     data:  _ty_.Optional[_ty_.Union[_np_.ndarray, _ty_.List[int], bytes, bytearray, str]] = None) -> None:
            """
            uavcan.file.Read.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param error: uavcan.file.Error.1.0 error
            :param data:  saturated uint8[<=256] data
            """
            _warnings_.warn('Data type uavcan.file.Read.Response.1.0 is deprecated', DeprecationWarning)

            self._error: uavcan.file.Error_1_0
            self._data:  _np_.ndarray

            if error is None:
                self.error = uavcan.file.Error_1_0()
            elif isinstance(error, uavcan.file.Error_1_0):
                self.error = error
            else:
                raise ValueError(f'error: expected uavcan.file.Error_1_0 '
                                 f'got {type(error).__name__}')

            if data is None:
                self.data = _np_.array([], _np_.uint8)
            else:
                data = data.encode() if isinstance(data, str) else data  # Implicit string encoding
                if isinstance(data, (bytes, bytearray)) and len(data) <= 256:
                    # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                    # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                    self._data = _np_.frombuffer(data, _np_.uint8)
                elif isinstance(data, _np_.ndarray) and data.dtype == _np_.uint8 and data.ndim == 1 and data.size <= 256:
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._data = data
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    data = _np_.array(data, _np_.uint8).flatten()
                    if not data.size <= 256:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'data: invalid array length: not {data.size} <= 256')
                    self._data = data
                assert isinstance(self._data, _np_.ndarray)
                assert self._data.dtype == _np_.uint8
                assert self._data.ndim == 1
                assert len(self._data) <= 256

        @property
        def error(self) -> uavcan.file.Error_1_0:
            """
            uavcan.file.Error.1.0 error
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._error

        @error.setter
        def error(self, x: uavcan.file.Error_1_0) -> None:
            if isinstance(x, uavcan.file.Error_1_0):
                self._error = x
            else:
                raise ValueError(f'error: expected uavcan.file.Error_1_0 got {type(x).__name__}')

        @property
        def data(self) -> _np_.ndarray:
            """
            saturated uint8[<=256] data
            DSDL does not support strings natively yet. To interpret this array as a string,
            use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
            .data.tobytes().decode()
            When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._data

        @data.setter
        def data(self, x: _ty_.Union[_np_.ndarray, _ty_.List[int], bytes, bytearray, str]) -> None:
            x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
            if isinstance(x, (bytes, bytearray)) and len(x) <= 256:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._data = _np_.frombuffer(x, _np_.uint8)
            elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 256:
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._data = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint8).flatten()
                if not x.size <= 256:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'data: invalid array length: not {x.size} <= 256')
                self._data = x
            assert isinstance(self._data, _np_.ndarray)
            assert self._data.dtype == _np_.uint8
            assert self._data.ndim == 1
            assert len(self._data) <= 256

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: Read_1_0.Response._SerializerTypeVar_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.error._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.data) <= 256, 'self.data: saturated uint8[<=256]'
            _ser_.add_aligned_u16(len(self.data))
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.data)
            _ser_.pad_to_alignment(8)
            assert 32 <= (_ser_.current_bit_length - _base_offset_) <= 2080, \
                'Bad serialization of uavcan.file.Read.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: Read_1_0.Response._DeserializerTypeVar_) -> Read_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f2_ holds the value of "error"
            _des_.pad_to_alignment(8)
            _f2_ = uavcan.file.Error_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f3_ holds the value of "data"
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len0_ = _des_.fetch_aligned_u16()
            assert _len0_ >= 0
            if _len0_ > 256:
                raise _des_.FormatError(f'Variable array length prefix {_len0_} > 256')
            _f3_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len0_)
            assert len(_f3_) <= 256, 'saturated uint8[<=256]'
            self = Read_1_0.Response(
                error=_f2_,
                data=_f3_)
            _des_.pad_to_alignment(8)
            assert 32 <= (_des_.consumed_bit_length - _base_offset_) <= 2080, \
                'Bad deserialization of uavcan.file.Read.Response.1.0'
            assert isinstance(self, Read_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'error=%s' % self.error,
                'data=%s' % repr(bytes(self.data))[1:],
            ])
            return f'uavcan.file.Read.Response.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 408
        _EXTENT_BYTES_ = 300

        _MODEL_: _pydsdl_.DelimitedType = _dsdl_.CompositeObject._restore_constant_(
            'ABzY8XQGW^0{^vE--}yC6i&2jv)yjpTDz@?^omehY;U?-+bzD7HJdFVo7^?K+ae;<N$w<P=*_*CxpU*DAhZva76)4B^uZ@l5kXKC'
            '@xh0xp#2X7K@gt=pT$4GGr7qoyPH(<U?9odGiSazKfZI$y|L%PA5*E$M;!~>ZsdA4iJ0Kj<JW1`V>YP;%`k|#WLixxF^@NK>8`g!'
            'rtj;MH}$*vgnEi_-)BNYN=>gx5!Yla*mji(;?pKVJQveejrw+-BX)&R7k{EK@FU#IkQNgW4}1f(_i}fAUl-HG)O-4-R#SvZDR?!O'
            'EYfcy>Ijp!w6vO7=FD^ZcI+cAm6S+h9PCYmuumNvG%GJefX?iP1HGH!Al?RtyXr?r-5UxM9p1uw4{i7nZ}`kD_>wi4*dC23Qst6('
            '%x_50#Tm4!Mk7g@fs0nXsAgAtK<1d8!@ZK(!ce4c>55j*l1NhDrNSKqx*b>1m5CPhVzginaf6yxDUH%YDwD$);~BYS1RRBzx~t>G'
            '8F(39fl~>>6HZZs4Oz@<7wd(dzicxUEHZi7=53}zCCaGRLx%-5Sr@csq!I2fch|VD(r2`BBC6tLbN^+_^hUW@cCM63zEW{29kXBo'
            'Uh7^07uCf1bLY;U8v}8&?5vYzXQR9{1T8&322!Trj5I4fj!Dytxm<p2jV$HMh5RtHo|rp32HgGvLKQ0c+`3bF6VcSgg3atx7M2BT'
            'hFHCpz{1PEBe0UKz_+LsQVEs>Dy=Z!zKkpxpw#7p)np*rdWSXhbK^KyC|_P&DJ&8E-N+kr7V>rj%`vrRnXX{*$npbeA=$WV)dPX1'
            'FiTR=U^3B)+7X(*%Zzc7bzr%$k|*nqLsk|mm-54cJijnbke!Wn;w+Q3)y3R!v<u?|$&hkwV|CT3tPf|v**+XohXxuUskW2eYG6;p'
            'F*pzNa0zno29)3}xB?6)1aJ+mLkn)fO}Gp1!w2vn#xCSCEaw_UO6WW40IBm$=8`ZFl5kg-)j<*kv8XX(l0Xbev~sf$G+8#r&X>hh'
            'F>G?#q<OaHPIJHR#hY&Rbcb6a8^%?S*N9+^*fY2En{U)Tlr_-VPRF(9>@#*E#r{cvMtG%QzBFC7#cNF8LGonFEHV@}Aoe~S9<e8_'
            'ppJAMV2TxlOmte3Z5m<K!ya_J*Tec96M^N<XRY?X&gDwyd5vwgOZ6lPLanS(AW^$n4bWG#yu_LTP6Tti(=h{w$-t<r0mp#^U#h29'
            'sq1pTu}cZQF}vm1^QdU=+=Yd^`b2T&UR1?-872t2n2D?CXOsJ8n&5(Nn#Eo-Q84m&te7#!QuiX9HQ2<d-<hrDxZ2?-P7Rg}JtQ7J'
            '_b1)+BPOg6w5`>V%M_(3N#eC=q}wOmG+`cVnj|J8x6l8~7XQ^Gj=zxBxNPfEDy^RBMYe8c_pXDca84G}rW%s+`3yc!Lh}WDH4wqW'
            'IPwg){h_Hamzqo<!OW`!e77UI+n|nAsNY}}7Bb04<@H)8>S#Zn7zE4Q>xB6GVhVmJr84j%su$BqHhNi!;U`Q5i;UU~s?9u3t(&nu'
            'rk1)1WALFd^=Fuczu{2~AKiwJ%kYV6{2#^o>X{44o7+IW!l$=8J!@zxzTH~&WxpkAznjnx)BGA97SnMz9{9y@bexA@lPFmjB`ebx'
            'KQtw<Tb{%UrtoEMCV7dQg-0Wz1^;xtz`9|Z$Q!9kS0~jhcFE+eR}etA@oy(1Eo9^`kKy8=vxC&Iw)5=I?&`17sZk^<qkC5;jeA=K'
            '-KUP(yfI|c9JT)i(5iY(>I(n>'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.file.Read.1.0()'


    _FIXED_PORT_ID_ = 408
    _MODEL_: _pydsdl_.ServiceType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8XQGW^0{_)n%Wot{86RhNv-TvL^|Itev{0BRvB`M6-p%GgKrr#zi8c0&8QV)Df;!dRHB;s7=^pxF?<_(jLcp%nD2vhvgcKn-'
        'A`qN7z`wx(<;VdJoH%ge0Kc!QXQsy<Cov)iB5k>+9^d=>eP31HI{o9lOC|kZ`k7weja;v4MIuz(Q@6S8iK^uU-Chu>SY+t~+alao'
        'j@aq<MD}jB@OJj?Y(70_h2oouh+-?Id09%&T^F9};)pxG^L|VDz6kY}?Kn)FI0+9CJ7f903s#RMeBa@IwXGmSOK=y1W|F1T*1iZM'
        '75GHw?2Y{U-K;)UFMU6I8)8~KjzeW9v52y7fao!r4R>YfnKdOmcO*vHa(T>+LdPBNg`}g}$Bv7;exy3SaM%4<bVN9=(*u^RV#^bL'
        'Cze^Ah&vqC>IN>X_38AHtpOoAR$al`CM}Uh-^*HA`bjH_x$pAOEfTt$*z$aOf6#760#-R~xq*|Vr3}-bGK}RV`C$HaKAkNZbc=(4'
        'ydW<QY$hLpokr)<CyudL81jCWK6-;=7Bd@Klp4(*jtSw3uJ8vj!E(x<t53@(<x}+%DJB>0Bz8IjYxKCI;(k`|rJu;vv)bg4iKpky'
        'xzm>IMOpgPK+=(EAas2Aca}c*vWkto+xVGFnx3+PUY4@sh(!Ia9e4_cy|^j50qhVX*qS{N@;C^Kk?lx@0FoQ&!z+RB@L2d0x01TF'
        'GZa3BCib6iB%a5^{*j&cTl?HgMD|WLU!T4g*|L$F;j1|HXp8$D(GoootK&qvX?6K67!?Oz*OT&%0WEF6uJW^bi9WDx^Q}|qS&GTT'
        '<JelCqOGNS5u#Px>TzEuStGFp1d;HA+Prg0?iDu5E>?*$g6(uq2iP;Rf}fA2(=Z8z@X+iOn&VFWigqfF&TOx4)mpWkW=o%!Z={z7'
        '&Vd}Eh)9sJ<eP43OLK2P9cO0RA$MpN5i-4&e`7tp@7d=wiajl8_+i47H*2q18>@|1c3#b;k+*Xe@;m9N<>f0wVj{g*fE~;38z3X1'
        'J$X$Y$VmP`em4OaxB_ZWgt*zA^dSWLE#X?dAdD^LW{vcM6$MG?2#Ye+(uPc(B^h+ZQi5z;Y6qbJ)-0KP-d|o+e%niKx%T2g2*?eW'
        'dWnsQ1t@pmN^luLS(G1IBGO9)0@dZ}<*J!Ph+C3J;22WgMh5D$yYiXWK6|QEY5;qM%ZN<1Tw_FmMSaY58Og|m?*O!1rhK-$v-U!j'
        '?MT4_-|I6(v2s}?K$s$wsffi`gB}NfG!}V0l5B2ij>tyJ?+{@<H;>5$7K%0?p2dMa6$U}fTm=JyRG-b$oEJDc0$9*y2U0nbSh%9C'
        '0LaYl>vN=z2p6j5mVi+ZH-;{x77?2l)lQYoRjXhJ?U_$J^78;*{Tum(fFl#kb1#-b(vctxMqS=#j-+fP-L+;3)iv-!*zd!Z6ozb`'
        'hzK8AJHlP~LYc8eRx_sS1qz$|4(Z5^Wnm`HJmue{Ib&<E^o%G1A{{6k<RhzAk0&^?7O3i(0pZa~PJJ@vGPx2Mp}I-#Yy*)@7kM(a'
        'BZElzj7K;ahujs5C`-&1@qxfJbr7(*tvrCdq3;UOE3zLn0}<J~Oh!Bi!YE!up%g^XkKnAFtqH9mZzLg{jGU|F&gY&N97ObIcoGr@'
        'e$16mM&W}fQyP>UQAXTowT!P>0RCXcL%5W32kIsM&B(X{JbjAAgMh8n8f@)41JrayRL$h7eAR$MeGID4Z*kWJ$0HDp)h4=`o>|W7'
        ')5$or9*3wx{*X?8UOpjzE*BH|&K-HLA%B#1J`R+4_VNp+|0*DbeD@Ae;rG*}60Ml{Y==P?rVUXgW6B^`n7~0gQA&}$&_+hersz&$'
        '!~~oT!^0bigCvaFiN_o`4XLqQW!K5>y4`@cZVQIyk9!eQF<hCq3ls;Ge*!*6-tkx`AB8Z;>O3U5u!C|Y6x@+W-ae{&nO!-`0Q)>h'
        'L4^D<HkE<geRf-f!AItrbJSKy5S+>^JDvh0FkcAQM3jgfnbU}o5c)iJ$Ag><QRB%$;P2>|CiXcxQ^e~)cEByt880cEsU@ti1Oz=8'
        '*bn?gSl2VbY;@KFBIA55;kuD6u=kLV20jdQK22fwG#LA2M4M0(4mWsd((e$yVA2hQvAMXVqIjW#v|_y13j@?_D8fV-24R`11+V~8'
        'X{tt)icUcir6B5Hlj!!~bO@{YLf<~wFA`$l2F!v>95{i;%(pLS3(CJB0C1IoVjI;rAzYz)V&YXh4O$W(^gs&Tr&}K2m)1GZ*{jbR'
        'nCYsHq_~O_FCHL&?%cp0VU5eXydzAKAa(*mLpv9@QiffSg{FGBLf;_(R+KQXY0yOnO*NH3+tsO*SHX5b7)K18VTq}-4FQ{@%Jq#p'
        '2L#H5R-%KH@0XR%H~I~sV<tI@Ajcn6T3v2j)lo6`7)ikij4PvR8o|G&xRW#8Jy;ZaYBmW(3{8y%4l?R`%2CqRZH)nYS{n<1Tj-9d'
        'jbq$#g3!$?6>TH@At?t^9g&H_afsM8tchE^+oN3Zgib;%+PNp^6dAp0D}SysvcRZ6h$PQr%8!z8)FtHpOM2vv;K26+PSRD&+exn%'
        'L}HZigDfXOaX!(>xBY5u@yfO5Dl7_)D6J2SG;asSW?In$o#?hG&s8BAD9lya+R(*1ut$EbjLt!yf~G?<1#gX(hm^~;HX@*?-cX@R'
        '(Fg}Q`fzu|aNZWQKkCAK1v&D>(R(RG@&a4V-vt(QRs#&3n}iR%!>RI89}*Cv^>u@g5aQ?yPnB(>IOH9h>92xbOcBx%J|&@`k|7Oi'
        '5<4pMBo4aBB0~;sh%cz5;8yjLw)8Mm0K)q02&A=y6ah(m6uc^h-q9GOoXe^ghFl8q32w$zhr@Ykv?sS0Qaf=78mM#{Fd9fh@|B0t'
        'Vhm_NQd=+@RFgca6dkIvroFF%B=Y(d6EwqsP~D!s1HnGp9vUP}gQE@jQdt8SVw)PS%3*o)N(4f<xhxL7MM4#Tf&A~~IHwB=RR_ud'
        'ZZO1v7C^qN$QkrHFaSI5?yJZE9RahxHsr~q<t2F#Qk2Uuu*Ms}x;CG2MAEe}2}|o|17J5wV%~LnT7ARM0QhmO+Ruhxqq%Lf?FQY|'
        'C+#d=tmo;H{$Ae3%}a%UgDy_~#N3-Nqq+OtsJR>NJ~VHdJ~=Bd$cN3-%oB3)n6^*;Lbqe`m$<&`h>5e!H)qmEaL+W4aG@oUnD}$}'
        'F@+5uQzqM^sC!XQHvSmF^DlR^GBxq3LCOZydviuV7fctQ3$#&a@vRAq`jz4#bf^*FI1;(|XLD}l!rRv46CMlAp=@NqNsnR|iU(Jz'
        'FZrNXv4ZJli?0M{%sWl~+!21*_WPRk36BX=mp}MjVvNMO-A299{940WZMB9EB}Hmyp1XGK>a`P4oM|+7thMHD<N74ouAG3<^m_AH'
        'v8GNU(z)8o%IfyEb$zw5zB);)`<AbsfZT)YAhq6FUD;{2UI(@G%j;E9MaPLtJvvKaYTc5)9x>`o%$-o9qV9;JL)Yo-kTh48Poms<'
        '<3?>`{kny5ca_9>eico1#UMI0QG=U{c|IBR3o(IqTzq~xBF0Ia_0Zb-#;Uc`Y+4(&)+?)%jC|$!lNh<VyJI!itnIDZ%4BLUoWw{J'
        'l-s*oTg}$a<OsMrBA3JCU*%uq-{s%rKjlB<zvaL7W~NG|y)!giq~SabmuPsLhItyEq~R(JOEi3mh8Jmgg@zRj0NcCfj_rONcWjM3'
        ';}`6^h=`@JH@B9#Y3M6+@%3$ZG5PSaR)pr+VzHV<v6`KXz=UtYAfv&z5gfjle|>TC^J#6fG$mg?<lFzI-pn3XZ%W72n|cW~r8G?%'
        '%?}=^2dX8b%0qf@&VJCg!Rre-ZtV4C@9PK)`TpLwC`8^cAu?W%EB~`5W3NTL-m6cI`$`MA*T$MrhCvxNeYCeYG@thte;!rF_q75a'
        'U9Ue-E&t>HS0i!w|A0}KFtIt9#?G^OBYrgG|3n2Y95xrlfcQ08>{m4WmWJO9ZMXT;DPz66)TJeM^*?EwuEcd6000'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
