# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/user/foreign/uavcanv1-influxdb-writer/public_regulated_data_types/uavcan/si/sample/angle/Quaternion.1.0.uavcan
#
# Generated at:  2021-11-11 23:08:23.189459 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.si.sample.angle.Quaternion
# Version:       1.0
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import uavcan.time


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Quaternion_1_0(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp: _ty_.Optional[uavcan.time.SynchronizedTimestamp_1_0] = None,
                 wxyz:      _ty_.Optional[_ty_.Union[_np_.ndarray, _ty_.List[float]]] = None) -> None:
        """
        uavcan.si.sample.angle.Quaternion.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp: uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param wxyz:      saturated float32[4] wxyz
        """
        self._timestamp: uavcan.time.SynchronizedTimestamp_1_0
        self._wxyz:      _np_.ndarray

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        if wxyz is None:
            self.wxyz = _np_.zeros(4, _np_.float32)
        else:
            if isinstance(wxyz, _np_.ndarray) and wxyz.dtype == _np_.float32 and wxyz.ndim == 1 and wxyz.size == 4:
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._wxyz = wxyz
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                wxyz = _np_.array(wxyz, _np_.float32).flatten()
                if not wxyz.size == 4:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'wxyz: invalid array length: not {wxyz.size} == 4')
                self._wxyz = wxyz
            assert isinstance(self._wxyz, _np_.ndarray)
            assert self._wxyz.dtype == _np_.float32
            assert self._wxyz.ndim == 1
            assert len(self._wxyz) == 4

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def wxyz(self) -> _np_.ndarray:
        """
        saturated float32[4] wxyz
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._wxyz

    @wxyz.setter
    def wxyz(self, x: _ty_.Union[_np_.ndarray, _ty_.List[float]]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.float32 and x.ndim == 1 and x.size == 4:
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._wxyz = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.float32).flatten()
            if not x.size == 4:  # Length cannot be checked before casting and flattening
                raise ValueError(f'wxyz: invalid array length: not {x.size} == 4')
            self._wxyz = x
        assert isinstance(self._wxyz, _np_.ndarray)
        assert self._wxyz.dtype == _np_.float32
        assert self._wxyz.ndim == 1
        assert len(self._wxyz) == 4

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Quaternion_1_0._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        assert len(self.wxyz) == 4, 'self.wxyz: saturated float32[4]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.wxyz)
        _ser_.pad_to_alignment(8)
        assert 184 <= (_ser_.current_bit_length - _base_offset_) <= 184, \
            'Bad serialization of uavcan.si.sample.angle.Quaternion.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Quaternion_1_0._DeserializerTypeVar_) -> Quaternion_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "wxyz"
        _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float32, 4)
        assert len(_f1_) == 4, 'saturated float32[4]'
        self = Quaternion_1_0(
            timestamp=_f0_,
            wxyz=_f1_)
        _des_.pad_to_alignment(8)
        assert 184 <= (_des_.consumed_bit_length - _base_offset_) <= 184, \
            'Bad deserialization of uavcan.si.sample.angle.Quaternion.1.0'
        assert isinstance(self, Quaternion_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'wxyz=%s' % _np_.array2string(self.wxyz, separator=',', edgeitems=10, threshold=1024, max_line_width=10240000),
        ])
        return f'uavcan.si.sample.angle.Quaternion.1.0({_o_0_})'

    _EXTENT_BYTES_ = 23

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8XQGW^0{^X7NpBp-6(%WC+(d1ZWLc8!lI@6OqUqr_)X0gGD6|<HWl@TjSV)j`s=JF*1@)GyYLX+sfPF|H0u8tUcL4tc{{$U_'
        '*arjt0r5Q-Bfr4D<-MNjnW0SGB0&6J*Ye)0w|rIe@%TS}m>a47<*%jPKnJ1YYOW*;<rC(G+;RORN)s&&FY~$kMrFRq6o1f7dHGqn'
        '^hx<qxtLG5F^gdSYQ}bb7CTxxnnfw>W^o7p{w`yNt5_y+nNPX9Txk@=NIv;{D}PqfQ9APX@{=;3b(t|rdYR$6{1a$@fnWVqWj?Vb'
        'c^C}*nQ;SVm}}5UG1eOt6MgrLjJR{Z8~Z{fv3$aV2QZ)wcwCA}F<pBiPJnfB+HRkJksqm&ku-7_{Fr|jYuSl;@P2G~hpWR;nsq&C'
        '+>pl|BTCu^FMXzs8zljFc_qJaw^oGPoK2X!jZ+w!zm@mO{G1Cu#sO2ou%d&^gQLwx(pQP*ei8>|KJEsIUq1Tp*vQBO!AYD&9#<sU'
        'Aw#P)F@hN)*e)k2)0ziF%h=~cClM!1feFP_mqhRx8zN&^U#&FG3@Wwbpfpjk1JjGr;m-AH6$Y4iO!FloH3|5RgqV<&s|HKcQ2NY3'
        '&K-hk{7fm-)8B%YGR<coQN-g!@xNw}8`!?1l4zh^_tRG?BM~^p)pepduNL_U=+!A4RK^_`Rl5?-R=FZ8>oaf)aBi1{8AmToLSnv)'
        'VS+z9VY1iruRq_~Xh2BFo(#ZG?lbW5t(h4@8f5j)t&PKxh2_jkGDB8Z+bz=NOzG=nPe@<j6!b-Gx(>NTHr6YhLwmvR3~EP_y(9|*'
        'Fa#C|$>Ny%Tx+Ie*zLIhg+QdyeQzObunoM$jI_Y25lN<TRb?KggA7y<2G&3^-<J@t*gzc<Ur8;s(>u&&2(=*n#^$YUvKS|ZY`wEY'
        'pb}z;r2>0CQ&1FHit)NZye>2;T1;6tOjwm;NEDEPQ#t;iP8EsJ{SGYFf`uVw7|RXFp;0aGnb_fjKt&t|dNpeLd4Qr=Fjy8C1BJ6O'
        'B!)l`wNpYPoXn>-lNj5?^!rZCi&w35mA1v};!Qe&{UjE8tuy&>n{MCvaJv*s`L#cAl{{~{syE0RM&ogu?8Q!*A9pK<%KVj@6!?A$'
        '1&3sIh!UpmRrSfj+8@!%r{Tyxj%t|SvNFu)qst|FroGJL`TP(Mx?Z<Ov3QC_aY?L+Mh1iua4-t(#Dnr6Kk4qseIB@&C|3sMc7Ddy'
        'Nv3=b6Crm~26T~|rhv|ELIPBCCs7>us@dbk-Ia!ncfxEx@EUsx2wyeR%!77y74KvrS{d-Fwwsz5o#v5b>Z~}+PHz=ZqbryO7qHn~'
        '+m7V{g#4TBUVEcvf|{{5pxYA#y^kTqDuoti(4J;5QI8u{{p%r%RfZ~)P!~oV>L*Z;gjuiStA-!gfe#@&0y+v}m_$Hlfi;ZP=_Q~E'
        'xTxmbs^fNHO`;k)<-XjJLsbpe!DH?q^Lim<^;%sO1EPjQo9DmF{KRjh`Jno~&-*2tA9Itm%*l(C=x*dCkQa#RZ5}0-0`EZYF_Wml'
        'g>&5X1vGmp?&hcNvH+RzM~lQmoZZgC5Xk=dS<(8mT%_$ndvI;1Jq;zD$~-t{BxAh9Kw$eQOyWfbRf0<CDDE36=$OT0h+_pEx8D<p'
        'qXj)~$0zOhl*MT~K7)9?ptE-U3B;*_&LNH$^rT&X3URier|tY1#EF8QwR+|e&ldC?;^~5(M?6{33y3EQ`V!(yK`+|<FI&5ptewkN'
        '&lPL$6~xO0eHHOiL0?0Bxu68`VnMGWzEsfH5ib<<4aD;WeG~CqL4SfcU(jpTuLZ<21zoiMEg_yN=ufSmKSP`==ymIF!=Bf%em4=P'
        '3%YFmUqPHK=&C)(nvKW0Jx`U_V+Gx?=el9z+qUPs*~>e9%i_;1{=(wh7Jq5+R~CP5@jZ)=EDDSJ7N1)D+~OA&pIQ9c;<pyRv-o`v'
        'Z%>U{;bJW;)<U}$-m8U2wIFI?zZRa>!soT{MJ+t5g|BPj+gkXp7QVMa25&jwf4DV}$nBViG!FO6v>CiEm+}$3rUq}y%P)A_D#g0+'
        ';@d((@A1Pe96J1<oO5}|@fBuYx>xe)Ex3ivp;d6{5xDeL#llnYGGZNg|77^$d^=xQTVGynudc0cY^=3gtL=8{W_xAj#`5|~du_eF'
        '-dfqXx!PJ^?_EmJ^waQQO_?uEx1{6Zeepq$B<_fNLtJw99#6TEM>Eox`xv)A6n`Az7gAJ_`V0M7F!=9%RMz~V#Xq<EaU9><?>>PL'
        'iZ9`I6t~dczr-2wAMsTtHV?!*+v45-`{kx(v-d-$S^bb{4t~fCUvA>J2k6$(5&5t$4M*ubJX7%Aj*p~nj5IPgT$cC?=tyn%g-b`P'
        'u(cs<Z46r#E%9%zar7CCJ{yd>NZUUe#?U(d1K3DVl>`m|00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
