# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/user/foreign/uavcanv1-influxdb-writer/public_regulated_data_types/uavcan/register/Name.1.0.uavcan
#
# Generated at:  2021-11-11 23:08:22.980071 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.register.Name
# Version:       1.0
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Name_1_0(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 name: _ty_.Optional[_ty_.Union[_np_.ndarray, _ty_.List[int], bytes, bytearray, str]] = None) -> None:
        """
        uavcan.register.Name.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param name: saturated uint8[<=255] name
        """
        self._name: _np_.ndarray

        if name is None:
            self.name = _np_.array([], _np_.uint8)
        else:
            name = name.encode() if isinstance(name, str) else name  # Implicit string encoding
            if isinstance(name, (bytes, bytearray)) and len(name) <= 255:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._name = _np_.frombuffer(name, _np_.uint8)
            elif isinstance(name, _np_.ndarray) and name.dtype == _np_.uint8 and name.ndim == 1 and name.size <= 255:
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._name = name
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                name = _np_.array(name, _np_.uint8).flatten()
                if not name.size <= 255:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'name: invalid array length: not {name.size} <= 255')
                self._name = name
            assert isinstance(self._name, _np_.ndarray)
            assert self._name.dtype == _np_.uint8
            assert self._name.ndim == 1
            assert len(self._name) <= 255

    @property
    def name(self) -> _np_.ndarray:
        """
        saturated uint8[<=255] name
        DSDL does not support strings natively yet. To interpret this array as a string,
        use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
        .name.tobytes().decode()
        When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._name

    @name.setter
    def name(self, x: _ty_.Union[_np_.ndarray, _ty_.List[int], bytes, bytearray, str]) -> None:
        x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
        if isinstance(x, (bytes, bytearray)) and len(x) <= 255:
            # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
            # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
            self._name = _np_.frombuffer(x, _np_.uint8)
        elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 255:
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._name = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.uint8).flatten()
            if not x.size <= 255:  # Length cannot be checked before casting and flattening
                raise ValueError(f'name: invalid array length: not {x.size} <= 255')
            self._name = x
        assert isinstance(self._name, _np_.ndarray)
        assert self._name.dtype == _np_.uint8
        assert self._name.ndim == 1
        assert len(self._name) <= 255

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Name_1_0._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
        assert len(self.name) <= 255, 'self.name: saturated uint8[<=255]'
        _ser_.add_aligned_u8(len(self.name))
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.name)
        _ser_.pad_to_alignment(8)
        assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 2048, \
            'Bad serialization of uavcan.register.Name.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Name_1_0._DeserializerTypeVar_) -> Name_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "name"
        # Length field byte-aligned: True; all elements byte-aligned: True.
        _len0_ = _des_.fetch_aligned_u8()
        assert _len0_ >= 0
        if _len0_ > 255:
            raise _des_.FormatError(f'Variable array length prefix {_len0_} > 255')
        _f0_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len0_)
        assert len(_f0_) <= 255, 'saturated uint8[<=255]'
        self = Name_1_0(
            name=_f0_)
        _des_.pad_to_alignment(8)
        assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 2048, \
            'Bad deserialization of uavcan.register.Name.1.0'
        assert isinstance(self, Name_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'name=%s' % repr(bytes(self.name))[1:],
        ])
        return f'uavcan.register.Name.1.0({_o_0_})'

    _EXTENT_BYTES_ = 256

    _MODEL_: _pydsdl_.StructureType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8W}=N@0{?YXU2D`p6y4%(yIQN%ss$Ch2ucN;SVifhwNQ|_ZS5B*$S}#=?hGcAFqy2of?yvM3j-E9{#W1h&StmUwcWfVnfrC_'
        'Irq-D>hEf;(tFH8)@3=1J(7bGG!|cI7=uTmG|AFjXs~8xN2?;zg@WB~2KK~0KD1x$qNx!{6SUtfXgi|PQ_vE*2IXz^j_afiDi^7='
        'yke&I``;%vm<TFA?4dQ&glersSZK)YM>`J5sgpIebpbIOBDg{r)s$!l%iJ9kt`zNBGrv#q6i?oQY-zsgPDk6BArM0XQup(Xfs-kb'
        '2rb&^F}Ejk(UQR4NDVDeqxq&uC^U(C<!n$#uo2BQNm2%u-!Zqh28mplw}!T+Ga*5h?{*t$CAp@OQN_+C`dNhLGG@wXBy`sXf6a})'
        'i5xg`O7Q$%34$*Kb>83)f(e(BKXlPm62`eTj|S}xlVhj)|9@+)z81P9Z3ln*?U_p?&8%sROOkh!FpWioBsC#Pkvxs+Z)TvVPSud4'
        'NfL2^lJe)~)><kfszF}p>Y8?*3M9_TBKlw7DB_r^?m5p%(x!0%_Lp4@>c@G=U-ZdX!KnFdDqFA(8E7#M(kGJ84pNH&uX=}kZIG+S'
        'Um_%m<UY`?`De;ZIaQ08y7*wi`BsjDdigF;c<5wQ_Qrps2mujoqAXj@N}a#ED1z^yo2$iZrdsY;m9P}atk@!?X70@5kg!{>A)<WG'
        'XLB4o2AKlKB(q268jeK=7|BwliC}ia%#u7UR0L><fn*ei%Cvl*Cg2x1>i$8h0H@k7x4ON&B;-L{bXd6bS>b)4{HzF3S%T}1En}78'
        '66XCNe{dD}?kez>y{BGjz;Pg)=2%s^MZ<D!5rIA8AI$w#+1T4%Us(bf;U2KYAV<Ts=UM)Q`=uDqMg+aSMHv&abxugMzQju?E6uop'
        '#VGHmEPMX|MSQD~4+Q`K'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
