# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/user/foreign/uavcanv1-influxdb-writer/public_regulated_data_types/uavcan/register/Value.1.0.uavcan
#
# Generated at:  2021-11-11 23:08:22.982324 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.register.Value
# Version:       1.0
#
# pylint: skip-file

from __future__ import annotations
import numpy as _np_
import typing as _ty_
import pydsdl as _pydsdl_
import pyuavcan.dsdl as _dsdl_
import uavcan.primitive
import uavcan.primitive.array


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Value_1_0(_dsdl_.CompositeObject):
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self, *,
                 empty:        _ty_.Optional[uavcan.primitive.Empty_1_0] = None,
                 string:       _ty_.Optional[uavcan.primitive.String_1_0] = None,
                 unstructured: _ty_.Optional[uavcan.primitive.Unstructured_1_0] = None,
                 bit:          _ty_.Optional[uavcan.primitive.array.Bit_1_0] = None,
                 integer64:    _ty_.Optional[uavcan.primitive.array.Integer64_1_0] = None,
                 integer32:    _ty_.Optional[uavcan.primitive.array.Integer32_1_0] = None,
                 integer16:    _ty_.Optional[uavcan.primitive.array.Integer16_1_0] = None,
                 integer8:     _ty_.Optional[uavcan.primitive.array.Integer8_1_0] = None,
                 natural64:    _ty_.Optional[uavcan.primitive.array.Natural64_1_0] = None,
                 natural32:    _ty_.Optional[uavcan.primitive.array.Natural32_1_0] = None,
                 natural16:    _ty_.Optional[uavcan.primitive.array.Natural16_1_0] = None,
                 natural8:     _ty_.Optional[uavcan.primitive.array.Natural8_1_0] = None,
                 real64:       _ty_.Optional[uavcan.primitive.array.Real64_1_0] = None,
                 real32:       _ty_.Optional[uavcan.primitive.array.Real32_1_0] = None,
                 real16:       _ty_.Optional[uavcan.primitive.array.Real16_1_0] = None) -> None:
        """
        uavcan.register.Value.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        If no parameters are provided, the first field will be default-initialized and selected.
        If one parameter is provided, it will be used to initialize and select the field under the same name.
        If more than one parameter is provided, a ValueError will be raised.
        :param empty:        uavcan.primitive.Empty.1.0 empty
        :param string:       uavcan.primitive.String.1.0 string
        :param unstructured: uavcan.primitive.Unstructured.1.0 unstructured
        :param bit:          uavcan.primitive.array.Bit.1.0 bit
        :param integer64:    uavcan.primitive.array.Integer64.1.0 integer64
        :param integer32:    uavcan.primitive.array.Integer32.1.0 integer32
        :param integer16:    uavcan.primitive.array.Integer16.1.0 integer16
        :param integer8:     uavcan.primitive.array.Integer8.1.0 integer8
        :param natural64:    uavcan.primitive.array.Natural64.1.0 natural64
        :param natural32:    uavcan.primitive.array.Natural32.1.0 natural32
        :param natural16:    uavcan.primitive.array.Natural16.1.0 natural16
        :param natural8:     uavcan.primitive.array.Natural8.1.0 natural8
        :param real64:       uavcan.primitive.array.Real64.1.0 real64
        :param real32:       uavcan.primitive.array.Real32.1.0 real32
        :param real16:       uavcan.primitive.array.Real16.1.0 real16
        """
        self._empty:        _ty_.Optional[uavcan.primitive.Empty_1_0] = None
        self._string:       _ty_.Optional[uavcan.primitive.String_1_0] = None
        self._unstructured: _ty_.Optional[uavcan.primitive.Unstructured_1_0] = None
        self._bit:          _ty_.Optional[uavcan.primitive.array.Bit_1_0] = None
        self._integer64:    _ty_.Optional[uavcan.primitive.array.Integer64_1_0] = None
        self._integer32:    _ty_.Optional[uavcan.primitive.array.Integer32_1_0] = None
        self._integer16:    _ty_.Optional[uavcan.primitive.array.Integer16_1_0] = None
        self._integer8:     _ty_.Optional[uavcan.primitive.array.Integer8_1_0] = None
        self._natural64:    _ty_.Optional[uavcan.primitive.array.Natural64_1_0] = None
        self._natural32:    _ty_.Optional[uavcan.primitive.array.Natural32_1_0] = None
        self._natural16:    _ty_.Optional[uavcan.primitive.array.Natural16_1_0] = None
        self._natural8:     _ty_.Optional[uavcan.primitive.array.Natural8_1_0] = None
        self._real64:       _ty_.Optional[uavcan.primitive.array.Real64_1_0] = None
        self._real32:       _ty_.Optional[uavcan.primitive.array.Real32_1_0] = None
        self._real16:       _ty_.Optional[uavcan.primitive.array.Real16_1_0] = None
        _init_cnt_: int = 0

        if empty is not None:
            _init_cnt_ += 1
            self.empty = empty

        if string is not None:
            _init_cnt_ += 1
            self.string = string

        if unstructured is not None:
            _init_cnt_ += 1
            self.unstructured = unstructured

        if bit is not None:
            _init_cnt_ += 1
            self.bit = bit

        if integer64 is not None:
            _init_cnt_ += 1
            self.integer64 = integer64

        if integer32 is not None:
            _init_cnt_ += 1
            self.integer32 = integer32

        if integer16 is not None:
            _init_cnt_ += 1
            self.integer16 = integer16

        if integer8 is not None:
            _init_cnt_ += 1
            self.integer8 = integer8

        if natural64 is not None:
            _init_cnt_ += 1
            self.natural64 = natural64

        if natural32 is not None:
            _init_cnt_ += 1
            self.natural32 = natural32

        if natural16 is not None:
            _init_cnt_ += 1
            self.natural16 = natural16

        if natural8 is not None:
            _init_cnt_ += 1
            self.natural8 = natural8

        if real64 is not None:
            _init_cnt_ += 1
            self.real64 = real64

        if real32 is not None:
            _init_cnt_ += 1
            self.real32 = real32

        if real16 is not None:
            _init_cnt_ += 1
            self.real16 = real16

        if _init_cnt_ == 0:
            self.empty = uavcan.primitive.Empty_1_0()  # Default initialization
        elif _init_cnt_ == 1:
            pass  # A value is already assigned, nothing to do
        else:
            raise ValueError(f'Union cannot hold values of more than one field')

    @property
    def empty(self) -> _ty_.Optional[uavcan.primitive.Empty_1_0]:
        """
        uavcan.primitive.Empty.1.0 empty
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._empty

    @empty.setter
    def empty(self, x: uavcan.primitive.Empty_1_0) -> None:
        if isinstance(x, uavcan.primitive.Empty_1_0):
            self._empty = x
        else:
            raise ValueError(f'empty: expected uavcan.primitive.Empty_1_0 got {type(x).__name__}')
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def string(self) -> _ty_.Optional[uavcan.primitive.String_1_0]:
        """
        uavcan.primitive.String.1.0 string
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._string

    @string.setter
    def string(self, x: uavcan.primitive.String_1_0) -> None:
        if isinstance(x, uavcan.primitive.String_1_0):
            self._string = x
        else:
            raise ValueError(f'string: expected uavcan.primitive.String_1_0 got {type(x).__name__}')
        self._empty = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def unstructured(self) -> _ty_.Optional[uavcan.primitive.Unstructured_1_0]:
        """
        uavcan.primitive.Unstructured.1.0 unstructured
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._unstructured

    @unstructured.setter
    def unstructured(self, x: uavcan.primitive.Unstructured_1_0) -> None:
        if isinstance(x, uavcan.primitive.Unstructured_1_0):
            self._unstructured = x
        else:
            raise ValueError(f'unstructured: expected uavcan.primitive.Unstructured_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def bit(self) -> _ty_.Optional[uavcan.primitive.array.Bit_1_0]:
        """
        uavcan.primitive.array.Bit.1.0 bit
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._bit

    @bit.setter
    def bit(self, x: uavcan.primitive.array.Bit_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Bit_1_0):
            self._bit = x
        else:
            raise ValueError(f'bit: expected uavcan.primitive.array.Bit_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def integer64(self) -> _ty_.Optional[uavcan.primitive.array.Integer64_1_0]:
        """
        uavcan.primitive.array.Integer64.1.0 integer64
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._integer64

    @integer64.setter
    def integer64(self, x: uavcan.primitive.array.Integer64_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Integer64_1_0):
            self._integer64 = x
        else:
            raise ValueError(f'integer64: expected uavcan.primitive.array.Integer64_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def integer32(self) -> _ty_.Optional[uavcan.primitive.array.Integer32_1_0]:
        """
        uavcan.primitive.array.Integer32.1.0 integer32
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._integer32

    @integer32.setter
    def integer32(self, x: uavcan.primitive.array.Integer32_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Integer32_1_0):
            self._integer32 = x
        else:
            raise ValueError(f'integer32: expected uavcan.primitive.array.Integer32_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def integer16(self) -> _ty_.Optional[uavcan.primitive.array.Integer16_1_0]:
        """
        uavcan.primitive.array.Integer16.1.0 integer16
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._integer16

    @integer16.setter
    def integer16(self, x: uavcan.primitive.array.Integer16_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Integer16_1_0):
            self._integer16 = x
        else:
            raise ValueError(f'integer16: expected uavcan.primitive.array.Integer16_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def integer8(self) -> _ty_.Optional[uavcan.primitive.array.Integer8_1_0]:
        """
        uavcan.primitive.array.Integer8.1.0 integer8
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._integer8

    @integer8.setter
    def integer8(self, x: uavcan.primitive.array.Integer8_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Integer8_1_0):
            self._integer8 = x
        else:
            raise ValueError(f'integer8: expected uavcan.primitive.array.Integer8_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def natural64(self) -> _ty_.Optional[uavcan.primitive.array.Natural64_1_0]:
        """
        uavcan.primitive.array.Natural64.1.0 natural64
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._natural64

    @natural64.setter
    def natural64(self, x: uavcan.primitive.array.Natural64_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Natural64_1_0):
            self._natural64 = x
        else:
            raise ValueError(f'natural64: expected uavcan.primitive.array.Natural64_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def natural32(self) -> _ty_.Optional[uavcan.primitive.array.Natural32_1_0]:
        """
        uavcan.primitive.array.Natural32.1.0 natural32
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._natural32

    @natural32.setter
    def natural32(self, x: uavcan.primitive.array.Natural32_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Natural32_1_0):
            self._natural32 = x
        else:
            raise ValueError(f'natural32: expected uavcan.primitive.array.Natural32_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def natural16(self) -> _ty_.Optional[uavcan.primitive.array.Natural16_1_0]:
        """
        uavcan.primitive.array.Natural16.1.0 natural16
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._natural16

    @natural16.setter
    def natural16(self, x: uavcan.primitive.array.Natural16_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Natural16_1_0):
            self._natural16 = x
        else:
            raise ValueError(f'natural16: expected uavcan.primitive.array.Natural16_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def natural8(self) -> _ty_.Optional[uavcan.primitive.array.Natural8_1_0]:
        """
        uavcan.primitive.array.Natural8.1.0 natural8
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._natural8

    @natural8.setter
    def natural8(self, x: uavcan.primitive.array.Natural8_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Natural8_1_0):
            self._natural8 = x
        else:
            raise ValueError(f'natural8: expected uavcan.primitive.array.Natural8_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._real64 = None
        self._real32 = None
        self._real16 = None

    @property
    def real64(self) -> _ty_.Optional[uavcan.primitive.array.Real64_1_0]:
        """
        uavcan.primitive.array.Real64.1.0 real64
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._real64

    @real64.setter
    def real64(self, x: uavcan.primitive.array.Real64_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Real64_1_0):
            self._real64 = x
        else:
            raise ValueError(f'real64: expected uavcan.primitive.array.Real64_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real32 = None
        self._real16 = None

    @property
    def real32(self) -> _ty_.Optional[uavcan.primitive.array.Real32_1_0]:
        """
        uavcan.primitive.array.Real32.1.0 real32
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._real32

    @real32.setter
    def real32(self, x: uavcan.primitive.array.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Real32_1_0):
            self._real32 = x
        else:
            raise ValueError(f'real32: expected uavcan.primitive.array.Real32_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real16 = None

    @property
    def real16(self) -> _ty_.Optional[uavcan.primitive.array.Real16_1_0]:
        """
        uavcan.primitive.array.Real16.1.0 real16
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._real16

    @real16.setter
    def real16(self, x: uavcan.primitive.array.Real16_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Real16_1_0):
            self._real16 = x
        else:
            raise ValueError(f'real16: expected uavcan.primitive.array.Real16_1_0 got {type(x).__name__}')
        self._empty = None
        self._string = None
        self._unstructured = None
        self._bit = None
        self._integer64 = None
        self._integer32 = None
        self._integer16 = None
        self._integer8 = None
        self._natural64 = None
        self._natural32 = None
        self._natural16 = None
        self._natural8 = None
        self._real64 = None
        self._real32 = None

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: Value_1_0._SerializerTypeVar_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        if self.empty is not None:  # Union tag 0
            _ser_.add_aligned_u8(0)
            _ser_.pad_to_alignment(8)
            self.empty._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.string is not None:  # Union tag 1
            _ser_.add_aligned_u8(1)
            _ser_.pad_to_alignment(8)
            self.string._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.unstructured is not None:  # Union tag 2
            _ser_.add_aligned_u8(2)
            _ser_.pad_to_alignment(8)
            self.unstructured._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.bit is not None:  # Union tag 3
            _ser_.add_aligned_u8(3)
            _ser_.pad_to_alignment(8)
            self.bit._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.integer64 is not None:  # Union tag 4
            _ser_.add_aligned_u8(4)
            _ser_.pad_to_alignment(8)
            self.integer64._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.integer32 is not None:  # Union tag 5
            _ser_.add_aligned_u8(5)
            _ser_.pad_to_alignment(8)
            self.integer32._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.integer16 is not None:  # Union tag 6
            _ser_.add_aligned_u8(6)
            _ser_.pad_to_alignment(8)
            self.integer16._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.integer8 is not None:  # Union tag 7
            _ser_.add_aligned_u8(7)
            _ser_.pad_to_alignment(8)
            self.integer8._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.natural64 is not None:  # Union tag 8
            _ser_.add_aligned_u8(8)
            _ser_.pad_to_alignment(8)
            self.natural64._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.natural32 is not None:  # Union tag 9
            _ser_.add_aligned_u8(9)
            _ser_.pad_to_alignment(8)
            self.natural32._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.natural16 is not None:  # Union tag 10
            _ser_.add_aligned_u8(10)
            _ser_.pad_to_alignment(8)
            self.natural16._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.natural8 is not None:  # Union tag 11
            _ser_.add_aligned_u8(11)
            _ser_.pad_to_alignment(8)
            self.natural8._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.real64 is not None:  # Union tag 12
            _ser_.add_aligned_u8(12)
            _ser_.pad_to_alignment(8)
            self.real64._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.real32 is not None:  # Union tag 13
            _ser_.add_aligned_u8(13)
            _ser_.pad_to_alignment(8)
            self.real32._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.real16 is not None:  # Union tag 14
            _ser_.add_aligned_u8(14)
            _ser_.pad_to_alignment(8)
            self.real16._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        else:
            raise RuntimeError('Malformed union uavcan.register.Value.1.0')
        _ser_.pad_to_alignment(8)
        assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 2072, \
            'Bad serialization of uavcan.register.Value.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: Value_1_0._DeserializerTypeVar_) -> Value_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        _tag0_ = _des_.fetch_aligned_u8()
        if _tag0_ == 0:
            _des_.pad_to_alignment(8)
            _uni0_ = uavcan.primitive.Empty_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(empty=_uni0_)
        elif _tag0_ == 1:
            _des_.pad_to_alignment(8)
            _uni1_ = uavcan.primitive.String_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(string=_uni1_)
        elif _tag0_ == 2:
            _des_.pad_to_alignment(8)
            _uni2_ = uavcan.primitive.Unstructured_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(unstructured=_uni2_)
        elif _tag0_ == 3:
            _des_.pad_to_alignment(8)
            _uni3_ = uavcan.primitive.array.Bit_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(bit=_uni3_)
        elif _tag0_ == 4:
            _des_.pad_to_alignment(8)
            _uni4_ = uavcan.primitive.array.Integer64_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(integer64=_uni4_)
        elif _tag0_ == 5:
            _des_.pad_to_alignment(8)
            _uni5_ = uavcan.primitive.array.Integer32_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(integer32=_uni5_)
        elif _tag0_ == 6:
            _des_.pad_to_alignment(8)
            _uni6_ = uavcan.primitive.array.Integer16_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(integer16=_uni6_)
        elif _tag0_ == 7:
            _des_.pad_to_alignment(8)
            _uni7_ = uavcan.primitive.array.Integer8_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(integer8=_uni7_)
        elif _tag0_ == 8:
            _des_.pad_to_alignment(8)
            _uni8_ = uavcan.primitive.array.Natural64_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(natural64=_uni8_)
        elif _tag0_ == 9:
            _des_.pad_to_alignment(8)
            _uni9_ = uavcan.primitive.array.Natural32_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(natural32=_uni9_)
        elif _tag0_ == 10:
            _des_.pad_to_alignment(8)
            _uni10_ = uavcan.primitive.array.Natural16_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(natural16=_uni10_)
        elif _tag0_ == 11:
            _des_.pad_to_alignment(8)
            _uni11_ = uavcan.primitive.array.Natural8_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(natural8=_uni11_)
        elif _tag0_ == 12:
            _des_.pad_to_alignment(8)
            _uni12_ = uavcan.primitive.array.Real64_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(real64=_uni12_)
        elif _tag0_ == 13:
            _des_.pad_to_alignment(8)
            _uni13_ = uavcan.primitive.array.Real32_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(real32=_uni13_)
        elif _tag0_ == 14:
            _des_.pad_to_alignment(8)
            _uni14_ = uavcan.primitive.array.Real16_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Value_1_0(real16=_uni14_)
        else:
            raise _des_.FormatError(f'uavcan.register.Value.1.0: Union tag value {_tag0_} is invalid')
        _des_.pad_to_alignment(8)
        assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 2072, \
            'Bad deserialization of uavcan.register.Value.1.0'
        assert isinstance(self, Value_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = '(MALFORMED UNION)'
        if self.empty is not None:
            _o_0_ = 'empty=%s' % self.empty
        if self.string is not None:
            _o_0_ = 'string=%s' % self.string
        if self.unstructured is not None:
            _o_0_ = 'unstructured=%s' % self.unstructured
        if self.bit is not None:
            _o_0_ = 'bit=%s' % self.bit
        if self.integer64 is not None:
            _o_0_ = 'integer64=%s' % self.integer64
        if self.integer32 is not None:
            _o_0_ = 'integer32=%s' % self.integer32
        if self.integer16 is not None:
            _o_0_ = 'integer16=%s' % self.integer16
        if self.integer8 is not None:
            _o_0_ = 'integer8=%s' % self.integer8
        if self.natural64 is not None:
            _o_0_ = 'natural64=%s' % self.natural64
        if self.natural32 is not None:
            _o_0_ = 'natural32=%s' % self.natural32
        if self.natural16 is not None:
            _o_0_ = 'natural16=%s' % self.natural16
        if self.natural8 is not None:
            _o_0_ = 'natural8=%s' % self.natural8
        if self.real64 is not None:
            _o_0_ = 'real64=%s' % self.real64
        if self.real32 is not None:
            _o_0_ = 'real32=%s' % self.real32
        if self.real16 is not None:
            _o_0_ = 'real16=%s' % self.real16
        return f'uavcan.register.Value.1.0({_o_0_})'

    _EXTENT_BYTES_ = 259

    _MODEL_: _pydsdl_.UnionType = _dsdl_.CompositeObject._restore_constant_(
        'ABzY8W}=N@0{`t@2Yehy^}d~YPE|-k6i7MZ6s6f}md~W11PFrR3nC3sf+gFEPsWyoBnKG?C_sV&0t8XObkRjO-E`AMH{Ep8O*dV%'
        'KmU1K?)G#=C;23~On%^%?sjM1yqz8GeD8hl8y5F?2`@qajh@}NeZ#<p%`4UpbocjkZSHw;*SgK!E7q>xx}|UHK+j<J_~^15dwaI_'
        '-mtx|d;IS43vVC4ZM<$&uI=sGV!u0eTi31YyLwmjcW>+&80_v}aZ}gkZT9oz+FQH(2kd3znZ&5RDg62FapRf9o#VHUj~=_WYjCi?'
        'XWh2J?t$@}ZHp!B$euMmDzEA3-n=1a!!c_&bPaZ`9VEkSFUMa$*uQQ4;I{tmJX14r^xmP7ef>RKdIo!L?OyTVEq#OA$1^&!EHWr_'
        '+|A>oC&!FhyKZ|h#@oo)4c&eH-RrvsyElyAHG0C@TY84NH>~a3+CR9qXT$ilqbIE$*t)HMeYgE$bNAZ5uEEUsXwS;b)-ByDx7qQm'
        'yk%>DchAP&m4P9*HeA}%d&}l+LmSpz`lNpA<NlR>+tzLFS-;l0aoc9<B{#Hz@S>Gj>sR{LuV`3NzasdG49|28*na!Fdk4vZxAv^>'
        'wuXwe8@8?=A5DzgpVn<27#}@9a`L*K!L^&adp8bd?CFCue;*$`?&_Ywhx@-@Z+{JaIm*{=?HeCWm1<;Q`<8WE?J%r8=-#r`-oin9'
        '*B{Z>-QP91wLf>`)Y|o#9(yM<myDj+-nC&vPw&QplQIqT?X}xBZ|>^fKJ#1K!ma*1d%<{}NsJAwv-7PlXlUFdx2?0o-O|%LZW8oE'
        '*AV@n*KXOm!TOfkHePU@Vd0U7M-d)ncvRt0hsR`iToxXW36IBy$K%4|@!|1=@OWZ)tO<`Ng~xk^$CJb3DdF+d@Oba=cv^U@4UeaX'
        '$NPlG`-aCe!sD6Y@vQK8c6dyM$NPoHbHd~D@OW-`JTE++A096Vk9Fbk!ti)ec)U0~UJ@QJ4Ua3r<I3<@A08XRV`F%13Xjd<aaDM1'
        '36HD8V>&#p36J*=kC%nV%fsUp;ql7w_<-=(8XULTrK5YOudCNzl)}%}4XoR?&Mp?RJ6Ic*kFL0(Yh$WDMgQG6(7howxHZ*J%fNtr'
        '$WmRsscpR*x^L;}wciAj(OzB?PTrF<r)F25(+XA}yHL?gow@wvt{%N_iN&zLzia#W=xH}~*-z~!!4rBFeVV^KAHTMHbN3cn4E)ux'
        ')Z&^o$v&|+T5oK$gL!E0VE4xE{`~fijXmr33A6rN-!(8ukCa_{?-{*!d(;qJw&H>IJJ45ly-(aRe%<)!DQgD?yLvZt^>2tbG-99B'
        'WwxchuJt|E<w$s=_lg#jTWGBh*Y=l$etDUx$-F%CO5;(RnF)J&=DbXu|7GUl%!=5;aq0uN_R?zITXY4YPH6$Mt0n#E$*c~V@Mlwv'
        'T}|?uI_<iy-i_VYb@z1-_LN%Ap5U)C)_!|Mys_k%KdG)TiOiKqBr^{vz4+LPz-BH$^qJvCL<^DqO+<@P^qrAL&0Lt`-x+PK2p1~4'
        '-hPsd7Oa`)nPujfXc4o&iD)4!cAh!b92YHcQM>lj<D$i`)HUXKb3(Kbk|ih2dbT;y-jr~ujQ3=}sfm`(*{(MynR`Xct34}ezp06q'
        '*-EZ8C!15E<#?tI_S;jUCA!kK%&F$y(Q<Cjs)?5Lxm<5fGqus5fMPb;Giswh4RdYRoNn$D{W*#JWxuVB{<O@eJ#$}kM)W7Cl)d(>'
        'Gon9N^X<c&Y0irN)RAw=>iZpZi{@;TivD1lR5|;p_vKaT&)m<P6a7)Pzs2qYdFi~W^<kEqbE7}@<ws`EKZnk}psIbF^UV3t%Z2?k'
        'yk{3yy$^GNsf%7(DjBD}qAq&5skR;FLUU2{!sOrEb8VY-@%ww}g7s@IHkU*%XO;TFUUf<IBDYXBnM=)z=q1sg2X(<rXjt%G%}P@r'
        'y^hYsBlgPr==F7>?K2IgF?vPLn=zNzw(Fx=vue?7F-@j9dPSeB&+OIB(QEx;*=kmqmS_u+on7@bzt$|e9cHyjN86YA_|CSFj<!9E'
        'ZMRut?jLQniq6Ak+eez_;uT9~pSjFj9&P{T>tEZ-<<Zu0sm5TgFjq#~*7%&IyWbXl+M54)NB-w+{x|KxcbVLGoio2R9b;yw@cT@7'
        'MqhN!Nc^1P;%AwmF|#8$kIope-`dw*drh4^D{ZfAv*&i$>ofKWd+uc6xjXFH6Q$1IRr>r%d&SOT*G$cR%`SV@?wQx^t^B$vd*z<^'
        'wfpCO?OuEJzUcbt`Cq@^ws63<fut8UV)v(WZf82)QtgbEY}3>jYP|WiS68+@+Z{EDlsC6l({pImnm`Ss-m9$bwt2U0&7$Vf>Xq-I'
        'qe?wkQ>hcQd&T?7EJ#1r{Gcmzdhy<d7Ns{kDC!V>9`!jA>l4EZ)U6#^Vb42?_G}FbJIC0<_CHy1|JKyd1WZ)hid_d~g&jm_2zDO4'
        'EmKvu#SSkt2fOEE(cVR|$PPR-3VSNEYyXnjWnB_C4f~2%H+|??XFV1ghy!Hfw#@CmjYu#g1QH5~q)8&lkQA7fNGel<8ipEy8f9ux'
        '%TOy&t1zui3Mqz^KuVc9)G^cv)G1SsdWL#|dS%i`Go%I5%Cw@Dp;e$&nKraBv<b8+(~fqAc7b+fI?%z;A<&^rCpsBA1v-_<Aj6Om'
        '$SBi?K88MlK4pe5#4sc<q^xU)8HNRhmG$ii!-&9$vd$f27!w#%*1J0xb_ncH*1Z!969N;;`gf9HQeaY92k&IqDX>#n5AR~wC9q3b'
        '7w=}+EwEczA5Sq%2}~*L<UI^~1okNF<-H7h1@<bl5BnJQ3G7qW#rqld3+z|c#|Ib=2pmxME=)5_TYoB=2nmjaL_*V4NOB~tlQm6-'
        '8jc!?8coxomZMgpR?~z?aik<tnx;e@N1a5Srb$uHQ7=)iX<DQ?(h_M+6Qh-*RiahX)M(>qlW5a4IodheCE7Jjj}DFwi4INEqm!dk'
        'qEplC$Z%vNGMeT`A4i`=pQiaU#4#i>r0p!mFvqaOu(tCUBOD_VBihbnjB$)fjA=WUv4dlW#13s|GbT7DBqp?-&zR(xl$g|ZMq?+('
        'PKlk`&S~u8*d?(`+gXj>9J?iUYdfzo#W5u@rR~hd9*#W{d$gU~*vm1^u~%ZRwsRZ%IQB{G({^@aKgWKF{o2lN9N;)0aX{NAactYV'
        '?g0vJ)MTzi&EXW>ND`>+f*Xqv+^7ls;DQ?q5ZtJ-pZeadYH%Yp8(^{k!Hrb@eK=x+8>w7C>Zl2B(3sD)E!XAW-=jLXK|ZOAW`YZD'
        '%m{Ae&lnfnm}_t&SY-$}t#QGPg9vT}f0bNtV=;moxfL-U+@Mce^FQwhK5q@@cwulO2umdFH_>(Z!Hwwqa>0!#w2=tUNtOt1&>18C'
        'x3dQ~^3R<;xKaH4^1+Sr*OU%!RCZnQ;KtmpEevi9`}bnRUR^W);D!$?=j_<w-;MI^4CS>n9R)X{mIx_M5>VsKx4pWO?Gf%94t2KR'
        'MnS9TIkY-UaHF8@wt2NpxNO+`%-}{r4;@wNVMcJHpr6cw^h4OG-&H)gF&zara&yp+GE}{{7!W!g1verXG(laCRDF<z0P%Db+{pDj'
        ';>9~B0Cv`?I2)8-w*Scr`rqN@n=r57Mp-L%9h4Pw4sMjSWvc47R1n-KYti0Cv8ZTpqpV%~m&`5-A7oA2SKPYkeCzy$ghCr5OJ`kv'
        'aAP_QZp1?yNGc?gQEY>Su?>ZqBt<wVxZwvm#8QSgFl7J7D99m-hc_s!5k@#%c;iS7Zv?T8X<m7FBVq&v^q$P}%(>gvb!E=DZG6*{'
        'y+k7Oyn)PFcV*7LHj^6Nv|wDnfGZRy`(@6#E3<s`Iaj4_yy2SkrQN;jw{Ga(kQ(sMOKrU+HP}5gxZ;@WdwSP*rv@|K(KkH<Irfr0'
        'ziS}XmD;eqw`)t!`jpQrqHEV}AM75uB-JxWr}u6hO!aQty!ldV^p>7pGId4j;XP02PPKOptnb<!w!C7zI18sK`_r2<mlG@Ra10eW'
        '9*heWxloY{6}eE+;)IF_aCM;~7b>beRFs=BE>tw1P!ajgg^FCL=x_}c<wFulLM5`0MAGh}Wl2b4De;IX<I>>~4v#2>M@)P9kc7@b'
        '5^5kUA+mh*460Jn5L79-;hIa+sR$7u9H3N9k~0fxlHAxk5S35bP^L0T=7r%;@v0oj%*!*c4(f5dhKgXkc1FdHH<qc@@wVWjcg|9W'
        ';{)MOA96)D9Jt_$Y`7vDuE>Tfvf+wsxFQ>_$c8Jj;ficHaKRPXa78v;kquX5!xh<ZMK)ZK4Oe8t71?k_He8Vn7xi&PHe8VnmpSQz'
        '8!mIwWlp*x8!mIw1vgxg4Oe8tWlp-xNmpdU71?k_He8VnS7gH#*>FWRT#*e|WWyENa78v;c;k>MvhfC%NNn2UB@($h8+{8_XCuyk'
        'DXg|}`BfzMn>!=5e(UDV-RnsYHdZ#Hd&R~Tm!$f;o|IbG)7#a*J=L?NYh(AU^)WVmkE)5d5*aSg;{rV{(BlF<F3{sjWVk?&E0N(!'
        'WVk?&3-q`W84gWwXu{k}WE{6GucF2B(F>?hMx$RS<2t)V&)d$&_v@u<X56QsW`<ujbH&v?gOwG`xM%d(tG905+}+iC!}h-J@w>;f'
        'MKZjgfW}=x0gdDW7tlz~D4^lZUO>a1Qv`enmb#J<M0O!82SnsAm$SkW1&eD%07cOyxnjto<bpmY0Hf@mg*k&8v;L8p7u-?NpRRd>'
        'Ar=2&Jg7n+bNcgp&|u1(|JYXrW|`M3M%4hBdB5OPwdlw}y=GOtSjj=Z^esp^ld8OmE*N}NwHM_DEtOK$*ZBp9s;a*ESd`K%3$kTe'
        'G+1oGHhha(3T8pKt&0xKE%+vUNea>|3be3fz~G_*CrersXHnsyB?l}Q9Sl1p3id1s1bE1Rs7nTb9#Vybme2<CfNbHSCAGq|nybv!'
        '=7Hux=E3F~^N?)Wq(jOo(`FuO9%hVrxPiIWJi@e_N1E%*_2ve1qq)gEDqGO$u(H~8m`9t(n8%vOnVZey&05oGy39JW-fS@4<`%Ot'
        'TZZb08kNbI9<#|j!E82LOt0B$`pgqezZo!tW}CUyJSkgP>!=#F88X|=lg(4iQ_XGWY3Au>*xYWOVV-H8W$rL{nrCOrh&ivsykbVo'
        'UFJFFxn|Tn&ph9}z>Jv}nirY7&A7S8yx6=XTTsn;Z4O>DJIqVX%goEoE6gj+tIVs-gn5m5t$Ce!y?KLqqj^)d?40vz6}@UE&6~|z'
        '%v;Ud%-hX7%sb6a^Dgsl^B(hF^FH%_^MP#PKIipC^t#z)K4?B<K5RZ>K59N@K5llKPnb`dPnl1f&zR4e&t=OZy1Q}+-4!!sK5xEY'
        'zG%K=zHGi?zH0WEubHo#Z<ueIZ<%kK?_>*7y1RB5-8Hk<eAj%>eBb=Q{LuW!{MhU>KQTWwKQli!zc9Zvzsi;gb$9g$x~pct`L+3t'
        '`K|e#`Mvpr`J*{t{$&1a{$l=W{$~De{*f!}>Tdf{blc6e`KS4p`M3Fx`LFpu^FK=I@;opP+=K8SJtz;_%T?=j)5A@Vg6Toof6F`^'
        '<Kb8j$9Xv3!wDWv^e7YXBoFuUaI%L}Je=y`-X2c#a>bh6baK<_pr;chnV#<9J|6Dt;S3LFdN|9&*&ZdF-p|819+rDJ*TZ=p&i8PE'
        'm#gaSrk|UBi$47*_xVB(7kRkY!zCUr^{~RjN{{lO8$2|6X!6kPVU>p#539Xgp?Ei4-E=+Vrz@rKukmny50`nk+`|<fuJrH#kJ9<C'
        '@^H0>2YPsrhX;GO#=}FroJxV4-fnsyanqZaD-ZSXFb~GV!#%*mwH_Yf5sT%K9<K9ny@wk--00yZ50CP4VjAvoaF4@L|2PoA>(L$_'
        '<KeL$9_Qg^50Ce-)+4f4mxpy8)_d6Cq1(eP9yWS8br|>fxW~smK68A0h&S2eVUvd^c-ZV=i-%qhTRq}XKG8$JhXD_R9=3V7)x(p#'
        'oG_Am+}z{l9=8R4+=#xs-NTbTJjKIPJ>2HuX&#<VCH`=`hi7<rriW*FxWmJp9-i&x)Wh84=^jt_cphSpCsiG|%foX#JlDghhv#{C'
        'zK0i3bxyp{!;3uJ?P1)*Jsw`{;U!*9jL$vJ?s0aH^I`rtQ*n`(dU%<KmwR}HhgW)dm4{bT8D6}`!)raf&co|Hyurg8J-o@wsbIRt'
        '-#z~B@juEQf2uk3W)E-i@Kz6R^YC^L@9^+Ws?d#hd3d*n_jq`(hxd7SzlRTaIiXs&T)5@JEf;RND7#!x>9P-c_>hMWd-#Zlk9zo+'
        'hmTXSe|*BjCp~=1!>2ub#=~ble9p_MPP^sBEiZ0)am!0pmlvv-_<0Xs@bE<sU-Ix}4`1={Rni&3*F1dP!#6y9)5EtseA~l!yqws)'
        'TaMgv<d!4194+Z`M1@_y>*0GIzVG1&9)9TIM;?Cc3nKl*!%sc@%)`$;{KCU8J^adx1e@IQ<(4nEe7WW8Fk8N;SoN<x{Kms?J^aqY'
        '?>+p%!yo;s)qnEvXAghz@K+Ci^YC{M|M0?6?QXeq%bi>9+;VrMFLzYG|DPWI<>B8R{^Q}l9{$h6|2&ea@E8~aXAlgMK{04XY8A^E'
        'j$t^K;W&ol8BSn0k&$}ENeuU5IGN!ThEo~t&2SncC5zJ;?!$0jhBFw>WH^iAY(}CM_hUGRVL8LO4CgVN&u{@Fg^LRrE@HTt;Sz>R'
        '8CEc?WF&Xdz|hFh#L&#JilK#JH6!hdH4OJ>xQyX)hASAZWOx80A&jdSu4Z^3!-E(e%y13ELl~)IJe1*K42I$13}CpH;Sr1^G9Jlr'
        '9mDkuH!$4Da1+C$80lp^n&B}Fk7alq!_5qjXIRTfJfn+Y9m9Ht4Gi53w=isEq@>Zqu!-Rb44WCYF!VBPWhATdM23Eb0fs?_Z49?E'
        'Jc*IO#&(7$GdzXisSLL<JdNS$j087sXLts~GZ~)6a0kPk49{kyzHt}Ba~Ph>Fv{>ehUYW9fRPTz3mIO-a5uv^!#xZyW_SrBU5=MB'
        'yo}-H46k5#CBv&2Ud>3P<24MgWq2LK>lxm_@J5C=F;eV!Gs9aL-pcSchPN}kgW;Ww<U8KQ@NS0pFua%HeGKns_y8j<j}J0@h~dKw'
        'A7S_?!^apt&Pdqf6AYhZ_!PsZ89u}CS%%LsQu+8i!xtF7$nYhGFEf0F;j4@!KfcEBb%t*+e3Ri@4Buw>4kP`K?=pOk;rk3fVE7@!'
        'j~IT;NDSmB3_oS~8N<&Re!=idhF>vK2KhC^Zy0{d@H>XzGyH+!kBnqO{>1QShQBcUmEms;e`ojyBh8S1GW?6--wgj@_%Fl%G5n8_'
        'eu&4xI5>ykkQ|CbbJ7x7#&HbCu^h*79M5qA$BCSDMNZ<l7stsQr*NFgac_>(IBATW&T$`(`*NJYaVE!E9A|UV8@V6HIULJ5&gD3d'
        '<9v<_IBAbu$Z-+J#T=J#T*|S6V<jgYk_L`OjwX&~j#V5j9IH8LlC0slKgVSpmvdafaV5tCIO&sI#c?&q134bV@nDW?I3B`DtK^{^'
        '592T#59a{KwH%M&q+9Yxj_WwC=eU96Mvj{}9>qz+<k1|D;dm^^<2Y{Scs$2iPI@L?9P2pNb8O(~=D3ApBPVT>9*#{MPvF?hv4x|T'
        'V=E_}lP7ZYa}00{a%|(cmE%dAG*7m3JelJu98cxAjpJz?Pv@k6ay!Q}IG)MzERH)k?&NqjCoPn_IG)4tT#iwW=W#rr;{}{_QC`UL'
        'B96N`#yRfccrnLIIBBH3l;dR_FXwm#$16Er#qnxRdMU5rcrC~4I9|{3297s!yor-`%9}af!tqv)w{g6k;~gCD<fNnWE{=C|yockx'
        '9Pi_JKgS0+X{vmX<3k)D=J*K5M>#&m@o`T2Dxcu^B*&*XKF#qNj?Z#@j+55P=Q+N>@kNd=aeSHMD;!_tq`UGpj<0ikgX5bV-{SZ-'
        '$9FhsuzZ)}dmP{A_yNZcIex_PV@_f$KjHW($Im!^&hZP5Uvm74kJXVh%da_p!|_{=-*Nn&;}0Bv<fPH^CyqaJ{DtGM9Dn2ZJI6mb'
        'iM#xh<6j*A=J*fCe>wh-<A0o#iaY@(zy*YW6i@<MkYv#^fnx-Y6*x}dc!3iHP81|tbdtcm1Wpz>Mc`C{dkdT<NEG>Wf%^#DSKthR'
        'GX>5PI9rgW(ftI@5m+v8uE2Q$=L=jQNZ{x~fr|t#7Pv&<Qh^l$D+Q??H3&2cGzl~dtP*GuSS?8UXpO-A1uhe~T;K|UD+L}PNC)XE'
        'fvW``DDWVG2Mb&y@DM?wNDmcwn1B&@xBvvM6?lXog``IcTqkh7zzqU73fv^{C_!>bj}~~0z+(j-CvdaC;|10V(oX6USSPSvV1q!n'
        'z%2qB1qmtj2y7B~g1}~hEdsp)TLq~qJyD=vU_f9{V4J|L0#6bc64);AWPzs$JXPQ}fu{*PU69_=?E=pbc&5O!1nv;HQ{dTx#Fy?8'
        'c#gnx1x5v)C-8iM7YK|Ayinjp0(T3H3)~~{Vu6<kl4W|Sz{><)F7OJ0R|>pJ;MIaOnqDLDT7lOIyk6i90&f&}lOVySHw(N);H?60'
        '6L`D8I|SY-NWJM@0`C@hkHC8c-Y4*Wfe#3ha{8dahXg(>@DYKJ3Vcl9<AQXZJ|XZ)flmp1THrGRpB4C=Ad#of3w%M~ivnK~__DxP'
        '1imUr@#$*<Ul;g>z&8cHCGc&5?+B8A`mVtD1imlu1A!k3{7B%(g0!H1BJfjzp9%b2;1>eF6!?`OVW?jV{6^rn0>2aZy}%y?{wPQ#'
        '>Q4fH7Wj+6Uj_aq@OOcK2$GEYr@+4i{w?qyf&U8ppTPeF$wzq-OoB@Y2`Ql@v?M91WfI3o94m30#PJd*NSr81R_Y{)dr6!uaf-yL'
        '68DxkO_Ida=@R#mxUa++5@$-BC2_VSxvBd}oFlPZ;#`UIB+i$(K$7&-g%TG@Tr6>k#HA7|Bvwk2p=yw5lxUJ@mRKdxBC%SMB-I*;'
        '`%7FVak<155?4w*K$1MwRT5WAJW%365)YQRM&cooq^ce&@h}M^@o))9Tr2SiNwQUsl(<gfdWjn(Zj`u5;!%<$tR5}#7>UP9JWk?f'
        'iN{N<l_Y1?C9zIoy~GBIZi!nYHcFDV>XFza@dSy@5?dsCCALbExq6~Rzr=vVpu{$bTP2<(N%CsD#FHhSBJos-+a#VQ@pMV@SGP+%'
        'L*khd&yu)9;!cTYOOnF6OX4{a&y^UJc%H=bC0-y&7VCu)FOs-hVqD@Li5E+}M3O|-OC??=@p6e*NW4<wRT8h3B$xFXiPuWJPU7_v'
        'Z;*JS#G52ZXT4eCEfQ~)c$>uACEg+NPDwIa?~-`8#Cs&(EAc*w_e*?0lBCuLB|aqaVTq4Od{p9N5+9c&uk{IuPfC1B;?okJk@&2{'
        '=OjsOeO}@V5?_?~lEjxKz9R8eNwQmCllZ#CHzd9(@hypOOMFL?1lM;Zz9;d0i62P(P~t}tKbEA$^%IGoO8iXX=Muk=_@%_JB<XVf'
        'TH-enzm@o%#P22kAn`{@0$qQS__M@cB>pP#H;KPX{6mtU{XZrCCGl^G|495-;{PQ6CrP8uQ(y{QK`2NCrJ#M`x@8K-C>*PBoWk)6'
        'Cn%h#NWAVOg?lNStZ<6LsS5X2I8C8e;dF)jDBM@!423fl&QdsAA*FCXg>w{^E1auvp2GPG7bw&zT&Qr7!o>=gC|s(rLSdysy+VUR'
        'qe7EHv%)Hc7KPOcX@xZk_gA<~;c|s56s}ZwfI_RnRSH)tJW%053J+GeM&Tg}Z3+)nc$k7wc(?)-u2p!1Lc78v6|PgbUf~9X8x?L+'
        'c$7ki!lM-)qwrXT$0^*b@OXu_3Y`jF3hNZsD{N5cR=7oBqe4cZM`4q~6BITpY*FY{*s4fU?}-Zi3Ihs*3fmNJRd^EV>|wjYlNFw#'
        '@KlA{6rQH=bcJDs+ZCRn@JxkgDcqrOr^2%pDev8-@EnEbDvT;TPvQ9rFCaNSyinmq3U@1vE8L^-VuhC|>`-{A!pjt1uJ8(lS1P<p'
        ';nfNg3a?Rkt-|XRUa#;5g*Pg^Nnujq%?fW(c&ozO6yC1z4uy9r>{NJ{!n+mTqwrpZ_bI$z;R6c06h5f%A%zbsd_>`+3LjJWxWaCQ'
        'Pbhp+;Zq8qR``s<XB9rDFs1N$g)b<4QQ=DpUsm{v!dDgcD11%f>k8jc_@=_Q6uzzS9fiFL-&OdY!uJ(^pzuS5A1VA;VV}ZJ6n?7k'
        'Glick{6gWE3cpg=ukdSy-zfZ6;dctZSNMa%9~BNL{7K=@3V%`ftHR$D{;u#3MS6k%RQQ*|zZL$Y@Lz@hQ}~}E?Lbe1X>bjpAvKhS'
        ')}$l2Oyd}hV>OP`I9}rfjT1F#3ZA5KFO8EmPSH43<K7ylY0?)wUE@9)_tiK<<4ldSG|twfHF!Ubb2OG~oU3u3#`zi-Xwn_LP~#$v'
        'i#0CMxKv|>#!5{Zgbf;v8ciC_8mlx~G*)ZUBV40#e~rsDF4wq1<4TPOXwoLUO5<vc2WmV><G~u&XgoxdPT@l}9;RV59<Bk6Yc(FB'
        'Nwe^g8rNxDuW^IMjT$#;JW7*(;iEMkqw!dc$7$TG@pz53nzRhNG}dXX*Vv%Zt#OOSMoqegJsO)do}jT=V~a+w##T)lhfmb#*BH<k'
        ')YztRtHzTw=^bv@c(TS*G@hz)o5s^Lo~}vz@OF)7XgpKnSsHg}+^O+wO*)8oX*@^cxf-Jy&(nCm#tSrQBEC@LMH+W&jBDJZ@nVga'
        'XwpY~sm9ARUas*9jaO>CO5@d<v=U#V@mh`7X}n(J4H|FMc#|gG#5ZfaMdPg+Z_{|Y#yd3LsYyfeT^jG!c#p<=HQuN3evJ=k(o_7P'
        '#)mXMtnm?zk7|5O<KvpN6+fZzNsUiwd|Kl(8lTnpoF<*c&ue@^<BJ+!()hB*S2Vt=?VI}^jjw5ZUE>=X-_-b)#<w-Tqe+4ByBgoq'
        '_`b#uG=8Y@BaI(xl4AUc#!oeVrtx!)UugVN<5!ww8Go(u8;##;{7&Qd8h_CEqb7aEKWY3~<1ZS2)%csn-!=Y0qK){c#=kWFt??g?'
        '|7!f7#{V=D$+2zgx(7&@uqJaQYMe0Pf(R4dlSp_8`p+p8I)y@~Q0Np2okF2gD0B*iPNC2#6gq`Mr%>n=3Y|isQz&!_g-)T+DHJ+|'
        'LZ?vZ6bhX}p;IVy3Wd(APNC2dBb-8^Qz&$I%_$VRyXq7Q-EDUYg>HH{g+e!-+;nmZg>L#edc0F8bko%-6uRl{rngflbdQ6399-=l'
        'r%>n~ANTk;g+lkZxyQ{_nsW+;?(uYwr&B0&kF$H6-Q(;O3f<%H9)I`vyRyzsq0lWCZn<#Fg;OYW%ZpoH-16cS3f*$#mLs<ux#h?y'
        '6uRZhEnjZ=a?96JD-^or%q?ebIdjXIQy_E-gie9bDG)jZLZ?7@2q+NFRex}-&M6Q&1wyAl=oAQ@0-;kNbP9w{fzT-sIt4<fK)Cn{'
        'gmcv&v~TVUuRsVd36=y;LL?!RP)X<{l1VH};+Q0kP2#vDj!)u*Bu-4Ch7=12)@@stk)!g~uFc!J$1}?_=Wbiql{w?K@l9XniNvOV'
        'vqWMbbJks%v#-shMz^fYY~9kma@#<6|H@mo_ILMe>|MF7>(=#My|*@8+S7Z>=50e8)?NCf{+>a5Lf^J^n|s!;?eE^WZFARP_lC6_'
        'x(2(}4sP%39tba5+1KB*rDw3`*6x*E{rz3rS6<ySxT0Z2{fgl0@yt1QWtNX#)mY!0POa-197tW9YG|OJQk%PbHx6d(@6G<NeO((i'
        '^z?2_U6E?6Z)pzBwLh=2mu(;H9vIJ@m#Mq(_VL@sGZ$x8_&?NT8Zu4MPn)zIYUXm2+*V$_v6yyaN!3P1KbO{PoK>OGUT;51R;0_A'
        'q`oRtVGP@~pB^_C-9@rwj*^P8p6oX@^Ab=L_WR@L+IdPO&alCLd&)tHAtuR|gOoTdVv{|iwkkq~p}*|6wN;ZREMc!b>x`-j5L(}o'
        ')m0V}OqH{rdS3vUz*PJ`ke3!n@UQI1?D^-=xeF-emx}J$0*mlfFiv|#-J(eA(Y-y_wpkayzl$V{SD_#5RhKNP)LqK=hd&b*S(a`N'
        '9<f)}FNw%pe8ya2+pdph%@WDN&CzG}>gFXCc#CFNJ<YErmS3BP?`#X{LqbHY*gR~ueWYnF9wJg_^YpK6<?=&HtSmNX?cEQOkSIu>'
        '5CqiOom!GnWM*0tK9{tAMJXa*BM6nNNt#-U!`BMJ;-<ApQS?0}kW!|O0`7GJb;{IJjJ;l<UYRt7)zboLWm+kc-YU?lOdAEy+XUK_'
        'X{UI3yFj}#9TXz(5a>{*lcM6C0-efaC=i|z$SBiCvF|>CK4pd|+&v^Pq|7iyxQ7LXl^LO+_K3iUGGi3S9upW-W(S3?cL?lIW`d&C'
        '69N;;Oj3Y)QeaY<ofMPaDX>$ST@;4iC9q4G-4uD=EwEdeDGD}E2}~)ohvLh71okMimqN;W1@<blkD|!?1okPjp907G1@<d*fMUf5'
        '1P&-OP2u5bK@d^GqmXby5-gPTC=8sG1O?T26#A`^1pm}}6z;8+1o@;q3h|~S!8~;yg>~yBK|A#xg>vg9!8vJ<!nbKj5KgN{A=_3-'
        'uuYpsVcIrHP))l>q1kpx@JxqC;n)sIkW8mXA=pkyFiggyuxmyV^wQ^1sI^ZL+%n`*cy&k;#4_wrNOf2etTN(J7<EJvlrrW~=yXgH'
        'e6qu%aOn<7kjaEcA<_v+Fv+AxVbMuR(8x}YLZLe)!6Cam3V-gB1cB`KDCD_Y66`VMQJ8Z|64bHBqtNCaN$|#AkHVSLoFMJJno?Ny'
        'ae}e;X-Zq!&k4HTuPIgK04KQmfX1|!gA};khL79*`^h(SZA>+#=s&x^Px(9jaeGEhxcxpkb87gL98Co~{}owaV1<ABiih?Nc5m$N'
        'Z)qOS=*%+vgeUGCzkNJ&+|A>$W?mTnG@iL<^rY*1HuiRJ2(P<gdtdkX-Q(f+FEg!~muFs`nHaHFyvC$5ug$z9`&H6@^~T_<qM*Us'
        'f{)&Lv;A##@U#D?Avrd%E_T`n!k<25n{UWFv31P%&lM(-xza8K4rj>6863)Buc@K?;ZTN!Kp74Jd?D9cwXucxXbQ(t*m^ZEh5Qjw'
        'pC|fP6^`dj|N2UCglH^LyU|Ea_U#E;jeHcfda$^`Y%`&9jNn|`b6x&@%3=i3tV_l`7WI)ES=7%t**-2jXe=O@fx#$)zH>f3HP5HP'
        '_=28;H{kewzlP?2L$1x-eF}U=qdC>L=5*hl=pIpffv<x1>4n(I&%A3hpQHi|qd9)hqTNw_?!K*x&&ip0E%#JKc1ANXykEH;bQN~r'
        '@#i}}&fGJWo0qvUR<@&#+Ky&^H0Pt$B5FDEU$hrmh#hiZNqmL|Ye`^Ba3_OjFFQB=QTlewVYf>&CwLN<W!IRKe2Y&F?`dw;qW&)M'
        '`>MA+wb)(XA+>9bcAi<G>Q>t?tw1!B({!IZ@;`60pSRm@{qHil?>hbO>ip~4eSdXirH$j?XTt0IqH{)~bB6u1=nOiO&Y&}GKc>SB'
        'Wu<Y4?YATL8~f7ZTSS($+Vk7(S)KOUK00@@@Z25t?1@t6?<#%%q`hKiv1_Jgzh;-cYWK|R_Evt~l)Z9K{M!9<zjm*^dS7(?^!%^i'
        'Z(BHE+lYkN>{fY>?F{9$G@aG#%C=;irpD}M+rPKvS}SO)u4G%bo5(!7T`xPz>1d4Ua+d9&7Q@!8g|=(I(UNY<>Z1hB)s$?4P=mA='
        'S%+57pEyMv*HPNM{6=k4)MD70wa%JC2BO`wgN<4p%GUIcw^-;mYhT>BpgC(yG+cCgITsGi!G*;Qw5?L(VZ)hhDQCY)42P3sHW!9-'
        'g^-jXkA`c<N;aa;BUkR2(PlE5HDl#{8FylS+e6tZn6XBEhmQC>u^q+STF#|`vDxB!g{{U+4qQupgzeAb*=!B2Y^&jOM`+e$)}=dr'
        '2HLK;W3k%{JzLDJduOzo=hRsHfm5mFT&sbR*yDRQ-?95Ea%|S<Sfin5r+lj0-pId^Yp3Vv+9K`7%nsaZdx==2*@i<XmjF?pdot`}'
        'jl+Hx=CGfOHmq}vhnVbcMwlVNZh{ctRzK&o)z7?ZrTn9@ZR@%R2pLLdu0-;1LWYv`{<y%%kjp;_{Os~i76utgRv8&e&9*P7AoHXg'
        'b~6(hO67Y$h71+99v@3_oaW$=A+JQA`QD3mSTiw|95R&3Wd&VW9OcT5r4T_mBim|((^M~`WVV@592uhV<WPoU*(0I=zpIJ)D{4PC'
        'uBeZT4hk9avM5e64{Zy2j^jdce+GN+cqT~Fo>`ZN48_r=++7O%MWe}~cR8%7y2w!B^E>ly&BXEY^Ecx6>=OU3<>zmBK8BE+jWh39'
        'K9YBS7JZ^IHdHAuBR(_Z&vtyIx#uf~e`O=tAu<#^Z^7Qb5E;s~9nJY@wnvy#)N&LhuP!n~b_8AytccIfU=0cE2<~HmeFb(9Miu2j'
        '1nXpZWXQ8;M6)({26MP`glGnLba{5xQhzJ`zS8EhDk4Kw$f9cv|GxRiP;1^@&LKm&&)ag?PlycBi*jf7+bnLBMTYXfFOCca*wJw8'
        'tm4Q}aK?xk^EcS#k)ix^XGeyLpI;ssDt}FBWT>+1iX%gFyS5M+n&0&^kfCAP>?CX}$%@-4fehtZBJg00l3k)L-fXSSM1}$wA`t-*'
        'L0cihLEGfW!t&NlN63(G&`5qWMZpNa!7?suD>Bfsum)}BBLh21AVcK_JHxzE@IcgNhzu2PF_pKQ&%rJ;nj0bzBj&=PIk>PqBov|!'
        '5i&$>q}_WWYCJWY3#sX$Jdj}qGL%IGf;I^e7_k;t;LFg|yk;Y0C@?P%UZ6~(iDLdN?#r0P(-AUMtkoSeTuXg~R?p(u2pP(EYT$tI'
        '=?jseT`|WJBog;+Xy;61sF+)0w&t~86l}?QH*)O$N*tRrwJ2^w&c(i%f2Sj4sB+hq#e*WSa9@NBQEJ(Uj`<)+@1ra^Kc}tD=MlI0'
        'Y|1vDQ<kLK7%?;}$km%-lu9<`XRD3)xq%~;9$1#A^*@nFY^oD+p4Pwu^R%+*SOsjY%(=61t(rxQYvqtGhjcll%OPD3={f?DF5x2r'
        'Nr!YDMo3pVrqYpybVb=Q4(U45kgo8hJbab*tI#Fs?VOktI@kgPFX(Ol3wrQIo_$Rp5y6|f|8}1LBA$C$pJKU}@?||adcyKiNqmRq'
        'c`_WD8Y^NrY`WCGMQ1q+sW_dXbz$iYtuyEhDMx2;bOu*6;V7mvxN-@uT!Jf?Fqd)(ar%TSl;8>_xIzi8P{L7LC?QK&p(KKM(S(Sw'
        '5`Et0e-lqjNQ8+8Gro-xR^s1h!ZT(PR)TYei=X8PD~B9mC5W<DgRqiqDWB6&kzLbq%j!zDR~Qhl+{$!WD@!p?Dzmt4-fideP)b|h'
        'QKcSc<TDhEB(os>#A4`qy$vl&Z?Oc1p)6e{8^K?YZVOW<hO(rZ89f)HQ!GsXlNI-$W6H!bBdTP@u7k27k9~8{woFysmVD06+%4L>'
        'C>9k<#3*mq{w1?3FF~Y)b<>BQb=G5{fjB@mMx3X}M&dl>*iJtAsnaiO-{}|k?$kLmsbJLvql!usoGMpM`0@<<bXkT}mLApWi&3N`'
        'k)$Rh6`r3^RF`Q&=M1OPRr?s#RNBX>hSfgd_*5>-WbRoeHFVz`G<}q0namZME}dy|WI@x#vrmp}XnJ-o*3kz|=V!GzXu22&%t6z0'
        'ho+13${aL3S7^GDj2;I~R|lF-(n{DCvD*?wpy}M_h0yd&#@tM3x{xtf2u(-8bYd20+A-#iG{#&}n%4Z<t1HRCE5e$a8#G;(o>nn5'
        'UC?&hY!+7snx2>SWufVUeliQv4<TPeF@jgr+t8x)md~vlDMA7Z0y9<YcCM_xEVFAN`=6|!|1zY#Dp|4XpsbiPG+ow~sjAyj0W@9K'
        'qP>e^QBi2RtX=z;%q{|dhhivdG3%xeJ?rwJ>FFrHyN=ZV@=2E?EXw!x*_YXz?)@I+bY~b5F!%cz-x-c6oimz*6($)K{-5NeurTQ>'
        'L+=;)6wNF@vrSND_<kNs4)>)F_baOEpYdf~Gm6UNCzH`2>U^=<I+E-xOX$2%B@&x%kV`=5Y-*ebq4V+55jq{z?x1!DwL7TYLGAM+'
        'gF2|)LG6{1P#x4hJJeoCY;{n(gW3;ms69^E4Vb#g;#)e}dF8fL{tmGCCN8@P%jlvdc%q$M9>X`-#Cfz+wA;jtzZJ~*yFpT$<FvoC'
        'd%9pJXSalQGiP^&ld32kn7F(l9eC9|>A(#w^PmIQ#Oc7p3rhzco<Rq$adcou2X^XaOQxY-;|Rfy5bOxSju7k!!Hy8@2*HjJeAp3!'
        'Ye@LVk%Ap5c!5d51w_)tBLx=`POG@p!-^DK(1RldJ5q3!NWu3c5?+G-bL?Qp4tDI|rD6w%N{9)CM3RzC8EOP-lt~c>I3<u$rXKYS'
        '^#b+Ew1!fMt;)2couOTzU71c|^L7e!D$|EPhCYElMd@eES6Ebb%wr5=0%OV!b%GI}ctY6`?qt|0uv6KA?Pf$8-mUC-_Au-b*rV()'
        '_Az1x?^D+B0}KZQ4k&VI!k24IXmVu@M~y^{CKskS(T-D^TvyLgFHx__Wv!gp#jToL)y~l_(XPowot!ApotnJT$I&Ozr->;&%!%nd'
        'tSMD)jAKk<OcO17f)k;6LX+CUPL7=tJ2kPNNfT0Hx3>2IdpPz;?9r3}w~rIQdY`r~#{rH55(gZs*`->!+WAYDYDE^iWGk0!<#^35'
        '*~;;nU9y$qHM?Z1!z|g#u7z~h9k<zWn=3}xW4zKsjN4ox<Mj~YHdle8>$uI1+w8c_j@#_G%||G=nJi<Jl%7md-utvfEkms`wWzhf'
        'X;Vk3?sWon%A}DNNHe6BX$xg!+mz`*2SbNIhcX$;X3q#pg&(s2W2ELQNClVq0=3HQzz&8T0y~r)<|LzR_eo_(w~Jwyz%FG6HRa3L'
        'PANN<y$pK=_9|=re&(meD@<FXl$pjfBZnq^{o16a_(Uy7tu<a#s=oDL9jD}Z>$WsU+Ww%)U2UAQ^V>AJse_|KqC=BsGJX<&Mq6iL'
        'h+{}%Nc$RIKJ9u$)2-UUu|r~qrtJSoPHFj*n&g3ZaqN=Vr725)ic{+Ul(zQ(dpY(>?A4g&l;=+={gP7pr@gYA?CW(RvFT}Q2{_pe'
        'E%V@Hk0{5<c7XyHC~$!S7btLn0>{dBfda?McC2g{C~$#-xd#gJHl)Jekg6FQQo9QcH>7jijnY<>E!u9B`y0~3V>fCy`Gt&fqJxKw'
        '@|IGJ^0Uh`%G2{8lqX|^awNPwMtRLV8Ra!480FM{Ljm{PQOZkF%H2-ZX-qFLsXW{nIbyjZmOEnkVMQ#D2*9;&PwVLAj$ZEQ<xX!p'
        'KiSRE%pJ|#(aasq{1Bv>o9TEG+(OgLv%M`Y&D`&H32Ek~`(I4$>C#p#KD)fMElb5NFKyA%vdc@`wdCyb$TT8xAA0QaLhCAGmq!tZ'
        'X{y#5=bG30u?T@$MX7Ny=6NhjE=EF6`|$}uA&M9uJr=EqQPX3Aix^8i7sH4X*27o^g*9T_^;l#hMq`f!Ibw|VSiB=fZjXgNVm$X)'
        '6eLD@j|D_x?Dt%3Bu0b}0wjK{B##px51GXI@$qE7I9EO!N2$x_&BwzkaSnYv#1iMz$HOggZhbuT66e{+!!U8qeLN%+=ikS}GjT3{'
        'JX90s<;TM|agKgGgcIlM2jQIQD54Xm@5e(sF)DwMbQrMtYcf}&#wF>w;6`C^qbBf!3vMhxaD$jk2`8Z9QuPiCPQOdl%LO;0lqwh8'
        'D97v%W{eANIA*^~*gMjL8@UxR9^9Z$Tk}7!nBm`+z3yNb{=qrPG7SF_|J$*O82-6)D`WT<o<BRozw|Zb8UC|hSDN8p`LzqLUQTxG'
        '@bAWa82;Io2q{hm{Qh~iS68yVgJ$?w*y_Qlmsi?0;j&@#l`;IQ&_hKG|El*>mf=4`^}YJN6=C>iVbDat@2~bCOEdgqJ%@5vVdn(E'
        'jx9XHf0q6iiQzwQD;9v^UsYSG!th^ki{{DjUlO}2X87l<i!=O}%DNKj<+0F49??I^!q|pFO_CxU`ON>N3U9<~2NVr&P*@|3aJcZs'
        'ks98}vQ;V$Z<Ma7a9c8w*fgo*H5K|7r=~)B9wimttz#t>4!dZLqoTNIjf>W}XpM{3xWWo9T63tDS8&l9S6;zIYmUxnO+G4+Bw!$m'
        '3MB1DR+dBsmJ$-k7I1KofP(}|KmyZVJ}M9^Y?18AR;38*TC6Tr*CJJ-uEn)ogWLMMHn%iaRM;X`xuP{z)xxCmidrP+S=1s~qNs&!'
        'KEI|#tE*{I4oGk?f-i*YV1xy#XmJSCvdHyT?K&3m(G-rQu=Q$y2KghRK2P+oDjd(5{`HmCtcb=EwHuA(WZ#~k)yPLts|O1V%r+A$'
        'uSZcXWiy&}$(YBYK5`?A`Z*`t$At&I*$-x5Fv_6soKH{9^Jy@?py%KfH(pz!hUR}muFc$i3VcSRIn}r3bl;xn9#MONuYwomh1jak'
        'ylXR`qymtlIeyQg?N5E~zO9PS$(eU8_f$o8Ml&(IU%4%E6}H#$=Q}>m+%uM&m$@-kR=pu=JDT~?oR3zEsO89i(Pn2Mw!ncU@fjMd'
        'C4nu$oeZA6?A-K6>Dw`f$_g}df+ulVc8xj7xA@fXp5|69>hA)-uX@{4i`~{8Qrps~%0afSL93ro7XTw^y3ZZ?pHu2zyPrT;o2_d='
        '-*x)m1?jId>l(zr&xF^{tZUF}hW)eZ{KUUD{|q|Q_T%ar9D;QX0%?`Gv{NGWFV|8YO}u<-CDQ(iwKXFvs(d|z{8|RZEh|nSFYUH$'
        '`GTOinsOZU8EIne<?{K8nwQ^bxfG}AY^%Al1o0LN{T9n;%r!^JKjCl#-TC~|0~NWj68Z8>wz5E0jH9*^7j{&VR+not8Dlh;^JUzL'
        '`EBP40mK>&>Cz!Vy3noVTpAdgCH5D#T84x@n`g5W{cNk@b2l@yDa>lhIhHb;0?(GtM9a0B=hRsH#qy<cSyI-!`HtORkz;e|SVfYs'
        '!nCWvzmaRF=jhrBle=Q1^q}Dot0mBr5tuma<B7wPpxa?Zz~ZpZH6G%wyBXnv1g-ffZ>uDXtyN*SBBXG)llOM29Zt1l=~O!o!PJs+'
        '*iGeWC55fW$5I@pIXGm<E751Z_o5xvOiX3A6q4d&DMV1t$hI2cG}TKPnQbP_SD;%I;CD4Ke?{%*#ufE((Lo_YUKYhk=Amst&v9HR'
        '?$2QFU0Oq9Cfby{OM$;=G&%Gxhc#6f87h2!XWp%uI9_R?>`VN+mY<;E`4~cOHqN|b`AFXRS@em<*ifa!i}=ipKilz<=AN${{*?_?'
        'm!-ZIwjIs+Xtqa~Q`B-42CptMM0NyT4y=gJ&R`7*><I2-fPDpa5JokZL<i5F5zX4*8O-6%5uzE~(dF4$OZ~0%`%0V3s)!6#Ax*9|'
        '{QKr3L#=stIfo48K5xrmKP6<JL)@qgDYOt73b3QN>~nEs$jLq*8nVxEQs}|SKF^@`<;gzJ*4kVopJ|&MSy<k>ED<ym_N`Fkxs1!&'
        'iVU<YtU;Uk$iR;IXgTMbSCZQqwpmuSIhD7YPv_BHW6cc_h!Jz)&>UP?9uf*shXPt=)Ocz(7gEzhc_2eYlFF6%GBh=>*$5d5%*%rp'
        'LQYwsKa2Y^W^tAkS*+DEjLca)TflFOIUs!cLS$%H%&`QC#C;puS&0g9%+|d2i-Ij#??#T@Ux{OLrWVC*h5{O1&c9i5VCAlzwUS}b'
        'N0hsl)ELn*9|YwJDHG1mTWgb)L)E4*r6?0@N>kR^2#=vzK|bCTqja$;KO=2~Y8_H0T{2mgOZBE@iNvO_Cl^znHk)`g4>Hvcl1`u2'
        'AzcpXa!8j$x{hq5t2`0PAzg<e(p63s=SV}k3TZ<Q={hoyuJENie3hm*ZTo_5-_D6Gp@S_z@Pgjvzn}+i<k{Es5fQwp`)}v@FXFkE'
        '^(hw9=<LlA5kf9QdY)W{rpCE)8B%dBL+iqF8Cqv>8B&hR;J6G<o%1N>GB{mMr_1SdIp?Cw8Rt&8G6+tQ(<yQ~Mb4vEk<+PgI=0FJ'
        't8kWLt1N;F=fM}MK1@_NOA%WRZxzmf2D4ZyoY~$MSB2B>b_rEDOZUH+Dx9UQSbP=E(zYy>3TJ7HmR5zcv|UTC!Wm|u6t`~r(6g?T'
        '3TI>^5uS2XC!hJ$DXHL3r@}skPMtH8DpE}_Dw#CFsWjDuAa2w?U6vk|<wg-tN>H(-M3PDtr4%L<6<(UqvHIGbjLJQAaw<C1DX8v~'
        'BU8B)lR2lD)X;r%(DYG~V&dxbx;nj;6S0myXgWWo#X-}>2w)DHc6y4gLhq3eO($t3Y|Gb5oV$i%DQJ3b8j9tiX-Ahk(&%zUIa>2;'
        'udXEht_WprZqRgDZd$c86pL6~9cX%9)|Z8*i)$!Wy`QogiVNOb5e>x|46q<DQ^juQO6kkex)xkRahCoUNkehoRxE&qVpVOaiiYBX'
        'TQpA%#U-(;VhzPZ%eoR8igg;3GZ>d6EK2tFsh8P=?)@GmbY~c`FZcWD-WiT5oim!06DAo|_MhY=p)e^(@L<2l=VxZgnQem7!uRu7'
        'W;oG5v0qWy{*0vJ_Zda??~}=B5OtEO?$;?ys<Ld(uN{*}Z2Hf#C17(lHO_<0sg7}MP6xF+sNF&B4r+H$yOYFoP<u7R@Ep|c#PA%{'
        'e)K@?alURq(@hrN($UT<x25uTfW<d)*-cnR7p=b&?d<aCy}>5Vqn)DNCT9GtV8-7KlAIi;{hi&@1v@#rCA6D4yDOYjMY+I4<PEvN'
        'Yv#!XZfKb+7q}+Q1s+~lF7WUSE^v+G0y{3S(=}TvE->9?#|Cz6V8;e_Y+%O*c5GnB26k-V!;B4FLy|v^5$qVj3(N>EV395!Be;lU'
        'TE(p%R*c|+9vmasF@hZ<*fD|~Bls|91c%ax357(G5=<Ft1ZtE?5$`u8kW!`|^$hg_^~$t{+J~*mw4<G&U7%f=PGazO3Un&dhdzcr'
        'fj&hkXUvyWRCdf`3}XUg$_{mc5r=p}*%9t!*eS46*@5k5L=@hw?0EJt>=D?b>@fB*Vgv6}*6;%i2Lui%a%sZXXG~~vWerD-M2#jF'
        'rZ`cJQ<_{?&rvT?ugPVtoEXKenq1Y+(Js-h$wi%<XwRLRywb<fC();g9X-s6-8`%*J#LI+OkzwE6?%dbiFrbkyuwb7of11WF`h{T'
        'QewBZ_W^r2_DJl}l=QZb6Q_Egwl2p3jsp@09Fy6lSGi*OOP5|n7P|y1mtf_%%r3#oahY9$mE$tI1gpa=!OE_Mbk~nOKJz_Z!b{M9'
        'j@Z0l#O4^O^bjL9S4ej~gow>mAm}<`vm-V;VzVPQJ7V(@N^B;}7-gg<la%y6Em6x*t4u9w?Qh!DQJ#C9K%Fvaqy^FpX=U0%0ogWX'
        'I?%z;A<&^rhEmxxg7V;p?Ee_)_zKd$Wxh16GCQz?VTZsDWrsP*DAj#Z+0pG{*d?$_*+EVD0=84ij%6>yUV**JTECz9Iq?e9)+lAB'
        'G0n)KNng1(sVPuV%Ta5M*OaGkJy^#nbKbfw&5^c0XmVE@r_}s5O>XMo=#c2p<e7}0!JpCASs3CNk{HsydY8|+9?^8Gc5v*F*r6%)'
        'f09#9{-h>h;9VTMBz9>^(Vya!_dliWJ-}X$y%Kvhra2|~Q$D|>eEw;#EFt^f$0ib+&Odeu2-yuS^B`o`AL|I&E@I#!1}<XYA_gvE'
        ';3(NHV&Ev*j*{&n1}<VS_lQB>hE(_)QZ-{kYImXGhIEd*QQC^KMca*Xe?xkB>_+V-zmQH&T=3<iis<AG^`-daXP4)br{_v1PsZrv'
        'NO*aC@|t<_$!kjR$*KK@0_M3Rl$RuwyM3&amtJ5>dAKifv~ou)ceL`uidG)ce{0>2){)B{x!jS<oz!%G&YL5dJCeC0nLCpCAxJVe'
        ')A1Czg(jJ2ds|$Rx!>&)lFUo@znCQR(pD@!$-J~JOGPp-ZPC(_%uCy~<RtURG~#j}dL;8g>nb9dNAZVgD%2XMoY(r12!UEfiE%Lk'
        'dMrmS#zjy2(Fs8TiWn_D7ORLc)MH_b7+F0R!HDzL!$<}NHDVO@SX?8<W{-t9V#M}Xv?IoGj|DzrboW>cB*uJ?g+pQ__*`Tp#)l8W'
        'BYvbLj~X8jn8a!F@l?JzWj-54smrI&$Ac<yDt$b_5~tP2gDr82eLV0Ir`yMaFmdXAJRlRN;m3nBaY}wXP!p%;$AdO;s(w6x6Q}J5'
        '!JO$Ro)c&B#{)YtMt_iU7?ApFGFPI;rRcffMqzNHCh&s`ZY)4>gLq5{r=8*w^$rVazf0811vjFEDi_=+NAM43j0<i!g1<}GJJN$2'
        'xfL-U+@Mce^FObc=--yT?qG=i!8yq?ME?>0+p&s-%X8;e#_umYe|CO<>1)dK`)9wdG{3*{YZqR)ob1@)-;Me3`?D<(Qk)Ff{qt<E'
        'u4H=$&F`<U)q@i*ue5E#Wy9tx<M&sghl=?9Rqv-Pzki0{d-Z!O!tc+*poxIpU+qDb=J&^X4wbIL&Iy1WTX=r|Ed4JMzkl9VEC9d1'
        's<u>x-@o7%&6D51Bz9HI@6TBm=l3s_btQz$W1)>antzgou?>ZqBt<y#dH+il-iTKYC>q|Nutpf+aN&(3HN27Ks#F}_C|yzEyyFvz'
        'P3_0UD=PFaPDO?EJPIm2=D1ivg~Kjd<ESVuTH~TME?VQFHLk3Ji`E>f#T8t%#uZm^(VC+(T9c0oBncSEq5?^~k(DJ;fu)25vgI2b'
        'B;X){5|F^OmyZg>%336Qvn45_sum5Us#=^`qN>Gp-Cdhonk%bmanI<oYc_A~8oXh9U-$Uk<Jl?}tzm_W(PP$b>Dt)aGq`O-_xR|t'
        'Tl%}!5B6;B9T*=?UK9RoFY8$4B@zv**Q{<?)6~$^oNj4sYFM?pKHbo~s&RF5W7F!UhSl}WO{-c~uSwUhuD8ckjjPhl&1=@QtXh*^'
        ')3CaEbxXRQu4!zkU!AV6Z%nUhO0RCIUzJ|7YE`<Wsd05nOL}#>VRgf*=K5y(v}sjCb5pvpxy3f$+|=06)Yy_vud%;2r0vP+X4{4R'
        'e|^)crq!z&TGpgn>TPcg^{ZC5tXkF3m~O0J-O|{+s(DR){hIow^qQtddvSC9YTH?QReieIp48N|#<oqpH8nQ1*s~fN8`m_a8(LPS'
        '>(i@Nt!c8oHa6MO+9BGZryE-u>zf;zn^)VxTVtE7wW}M_^=lf|G_F~bPB%2Js<*b+H?}mSn;RON)3)7~^!Od)*U|lbjY;KI5lPOo'
        'ib%3V6%pHfei4yYS45;7a^r9tUw7EyHVafj<PazxlIyM7g+t<_DI7~->(xMM@<&8{p6FjyIG!{8>nkl15{)HlHyX*wzCA&!k&mKQ'
        '4;G1;Z6;J+0Hj=wY&7eVF^@%k<VF_tb56F83lADy31(n0%AoI@PfyMBX)wN^=U`6}FXmB0^S>e2X6`-(KBLi`>RWTVZ%=fOsJ*~f'
        '!4731u#uT}ZRV3yfC@Fo?^(3ptk2!IRq;7F^RDHds>sf0CWiMbhe=cc&xk+Y@p0y!vE01Ojj^(F8ByEO%#Y@Lv|2<hNB)a;mkWV8'
        '1eU~SXt0(9wgh)Fc=ob$(;ua8#~eyo(98**#AVqv<|N<ZQ^R|jTeYaa3;e$7ZBH$BAALyS08v?qY$1tOKZ7wqqSADqJMurLT+4Pp'
        'W3e_{NP@oW^uG)8jb|2;h<~36ub){+qSXxhXVv+cmTmqSbf)dc6_Pjv3rPe@HgjpGM6PA7r957K`PNG0Sr%(+MjBfA0uuSfBZ^yA'
        'oUvcpZP|JeL31_bNdGhP^4iNKP!=^WztM6zWz*SKb9Er%Ef)GMmO`3qj<T)7;rg28Gip6l<ibj1<1^V(4q5G!+Dcs5QAr+SuFYhO'
        'LSD|7aVO@tovXYMYc%Aihm7<>x0Z8hU~IOMLSd_ASnsoWHd_-R+iLjS%}gZ=)5vm;rBt%Ov!zr2a;@e$HP(Ky1hrgRn)PnJWA|6&'
        '*j)Zwk*v2c&n@t8<l5;uy0*e>x>yx}py3c4CzP2HdOPd`xWkgL@?k|t?y$}^9s=FF83D0`W%{sst0YjfRbjUxXm+=gRd*sOP9$aN'
        'L{bjHT%K~+P33t!g{{ZOQXHo_IAq8x(PzH*q8-*uOl7v5o#JCDL{QGiwi@9y)yvVDZ6?fD7+n<LcQrA8MeXOt74>n^K_Nq47R5>C'
        'p>09Waa<_w&tUIeTC!v&+LXIXfxl=pIrJ`vHB}cGDtvxt-mRH9UTJ~yOZ>Z*pAqBv7(#9~&b(v!NZ$Eb^ohpUP^C<l_{@wy+wqa+'
        'p06DKmCX$(%QY@+JDT&+Y>zOfsO2c{pt{Hq*%5d-up&M?gEb_uBe;(N_7&Jc7}Z=dOFVl<G;4!rFo!!wh-Pp{muF`!^|#XRD{U^T'
        'A~IBkyu{Y<@0*VdwdURB95R&qye)_Ql#tsFaicOU+(Kk1z>eZ_+r^QgImvB1mF-1g;U1jI_6#m%p33%Yt<6PYo3_c3h2^cwGH*j2'
        '<q9RW%ebtq$Uw`&8nl^@4D6VXbauXZCCRj5n`K3^Q+d1jbRNGr*4z+*7%>+P&B2A`A)yd;DB!_Hji+XFAvHae2QpNoU|oqXLsRpb'
        'jgX<hygYazB=Hscv$!u~7H4Uw#ab;xft|&(1%%R=1Hz{-M22?797~W$+_#~fm54saY|U%GDA<zqZsgegl{hwMYEj%~DBwNj{F`NC'
        'R_@waOGgHMM9Gp#jS(I5K~Nu(QV;z^!8S=rYi$Zsic;^UG^P2C@EDpEBtT9v%FmnfQvgS(xFn@6CX;2!YaJ&f5}TfUe4M=2x4`7J'
        'AknRWx;9$>;GwSdgPXUf`n&u3y9c^^2fNm7?oRde4t8(s?jN{+>amwLUUbo_rb|*6`^THdXXCm(?|3I3>~JxMi#c4(;bKQNE>@nW'
        '=5Vn?5f>{bT6Co0Vuh?Ohl?E<xLEiKAHI0gd%1m`x9{>qX3@chA$Xl{^IzwK_xJ2e{fG$O>-~56{MYu}tNj$qy~3;hkS4Nx^a`J6'
        '(wMUURs7~`|BGIp=Rr?tYOIK!vgzsey*tZ^NQIn~P0ye@8F$!!MlWb;u5U~?HZ`}jG^JNHrqip|q#KB9(vWUyPB#<tqj6PpbA66x'
        '(YmlSi`E%5i<F~TIGTl1YCVc+7EYtpX|y_x*12f3#%Ud{B!*LGb?U56o%N_yXLX9Kj!3h>imauGG>f3fdhkWd4--Y!Qk<K^Tah(j'
        '=q#2ZYqqz=Rb=(MT|!0H()}-{B5P?Y7GIIIv@J`e$XeQ>rB!4tZP$`3vWCeq#jTq@^sFnT$Qs#5T&x@m%O_=ZN-F-;sjyF>Q|HX2'
        '>SPm)%4bb*DpNKgh_<y)mt}5cX<J0$5>$9Ak)-lfDTN6|MYtw(tk!xbqtaiUoC;8N3aSC-cwR1_WzP95HFVz`G<}rhv$&egu4Z%P'
        '9I>Mhn$FLkanN)zZkmIpowlZ{)_mkc(@9zh+wyfY=dPz&3Ywmqo@RMy+A;Z#G$vnB`q=#1t1HP2EW+lS8#G;(Hdie@%_0_82b!Lj'
        '^<|;y;(D4@@29Mu=7RTDL{D=DIV}jxRI%H+vJJD0vjx}FoTdLo($k!`6$_xJSyfxAqNlmw7R^&nb4l!~SWolNvaW=lW}U|53^M2l'
        'i!#f7R%kYRe7{H8;~7T8(EWaHd4^+3=Zq#5jY&o-50jkaG$sX!U+fq8)X^+&v`tVB`hFfuLnme`_A8Qb$Vd`G$SBf6NG78})Jalc'
        's8g6!Wr?PDo|s5%ddCTiO*Cz4EF_w?%$_da(6V~<>c)naOHvm{Kh91!{qPBnZtCE92hTfr-of(@o_CUp4xX=un4*K{otUD7=Z_wE'
        'K29hOc*M!#+d$f_<+fq|uCe&WFS~Ke=%VF>qTOH~|2WwAd9=H<Tg!~Uea!efNRlJuv?sLtz+m@hw~=-OXm^s6s*tQqq~YbGtv*?~'
        'sWP&1(cRZP_{t3}^WZDj6!Mj2%c@oN%{eym@WQf@hi9;nYaAQdv5}qV+fuQS=`K4yvg0E=KC<H@J3g}GBRf8_<0BtteB>I^LvoyC'
        '$4OpbPI3W{b@4dKMfBt<ZuPL@Bp3AHILVHa>^RAelk7OjhdC!X)P+naB$AZk%1|RvqfCmJ$0>o7GWDous28YLrZp6XY*nTm?F{V#'
        '?aFi#hqzOqQ<*;WG4u)aDN1@{zTTv=V;*A|6Btu=s1uA>%oECva3{k~ft|_@Y&RpS@@{3vvxi}iz#e6Xv5yfSd7rX|A7D5ja6pku'
        '6TWz5LX#_NIBFznG`TRviR_%x<hpu}dWm{XE^Fn)X>Qfzs&<ZciFQpc>f}Vc?$qR!K8`+#K27}WVNU$&VND5oV;o}=W17g=6P#$&'
        '6PmOqc5>{L*r|zgO$wP3yS2R!*u$|$VvnY@yM3Hk-TSn4ISz0fkT~GD)Gk@eX#*@>vKCqF(zRT=mSa=9bS=lGcIjG<P3_XP4zqME'
        'yB5-2cZ_PssIC}TkFi+~F-CQTJljKvQC$UQuwzs^Mzv#9J4Ur*R3D*?YO;(`T6;1{ne)>UwG6e&)S}k@rcE6s%hw6iDU(K8AkC0g'
        'rY#iJZBwQL9Sj`;9m-@VA3h@}nSRLrkCC>qAWdNA%k?U=13MUY2<%XHn3Ih1<tLRL-7bb*0=twQ)RZskJEiPc_A=}h*sHAd`<b6u'
        'uP|+mQf3;{j2xQu)qInh;uEzTwbpn|$^O=Zb)3@gt=rNZY5RjFceQcK?{CxOrVfq{i4IMk$@nyYjJD3g5XX?jkoGmoe6sh5rdzdx'
        'V~4~JP5gmLPKo`Kn#7WKaqN=Vr76#UiW7NYO51yYy&QWb_G(OXVhRu`KoTin+AGThe{W49vFQgVE;bXqp{0-szM=x*wEE^WDGuAi'
        '><sW<pXeCiE~wyw3NEN{kU@oe-g#WY|IbAi92wk27hH6~k-;4q+(j3T%IHGgE>`%vST$o8Yqzf9E_RMvSlYj`Mccx1e;0drY+*62'
        'XAs$mO}>2ea-YcFT%qc=zj+K)xBU&|wsqaK2d>LJGjr0W&w6&Zc*mwcF}ok0vOjM+OW1$@Lccyt+J92?>!7m#Je+=gmA3!fO21Ae'
        '?LQOr>z|j|f4)G!o^h=G=dbkZHOEm?^lKk6*xTsW*Pmej>8D@6PIcJcNWUgdvj2S3{<<x@56@J2A8x<v8K84-A{3x-|NYh*GCc#S'
        'ZM{8PdsFMTS_k&@4y3v^Z%*}X9T?~#Z~E{-%5O9^u&u9eYrpL&wQhTAFw>oinosrhZynsae(UBH$6UK@OLu?I`tS<dQ)*pzs=LRY'
        '-Jcp*-?h1`e;~EBKjp&$1DE-&*n!$>Qr3{J)IeYN`kt=M_QHYg)Ye=4@9p4hA1lU3Ph30LwQ=n&J>8o(_`@8ZLlJ;1Mlkon0GEs&'
        'e<OM55q;hLU4vWu$L}7GUAS`7FioAe(yZCb?LUI%$_kn$9W+CpL6hTcG%vn=4Bd2^4HwZwcs$L4QJM`Os!1e*JV+`qP~$@uncJ_8'
        'Cr8%iKFq^6VxQBavf}>%B<t}Y;0y!+'
    )
    assert isinstance(_MODEL_, _pydsdl_.UnionType)
